### ISSUE TITLE
How to upgrade nextjs-starter-medusa to NextJS 13 App dir

### ISSUE THREAD

**Issue by imash96** [medusajs/nextjs-starter-medusa#100]
Hi,

Can you please suggest how can I implement the new NextJS 13 app dir. I tried but got too much error.

Thank you

**Comment by kasperkristensen** [comment]
Hi @imash96 

the app directory is still in beta, and as such I won’t be updating the starter to use it, until it has reached a stable version. The migration would require significant rewrites, but if you want to go ahead you should follow the upgrade guide from the Next docs - https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app
