### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by DysonMa** [medusajs/nextjs-starter-medusa#109]
Hi there,

I was wondering if you have any plans to support i18n or any multi-language feature in your project's roadmap?

I understand that there are various i18n packages available, but since I have forked this project and added customized features, it would be difficult to merge with your new features in the future. Therefore, it would be greatly appreciated if you could consider adding i18n support to make the integration process easier.

For this Next.js project, perhaps the [next-i18next](https://github.com/i18next/next-i18next) package could be used to achieve this goal.

For example:

```
import { useTranslation } from 'next-i18next'

export const Footer = () => {
  const { t } = useTranslation('footer')

  return (
    <footer>
      <p>{t('description')}</p>
    </footer>
  )
}
```

Thank you for your consideration!

**Comment by kasperkristensen** [comment]
Hi @DysonMa, there are no plans to add this to the starter. The starter is simply meant as a starting point or a source of inspiration for how you can build a storefront for a Medusa server. 

We will most likely be revisiting the starter at some point later this year when we start working on implementing a storefront component library - https://github.com/medusajs/medusa/discussions/2856. When we do that we will definitely consider it, but I can't make any promises 🙂 

My suggestion to you would be to implement it in your own storefront.

Closing for now

**Comment by mjaimes-madbius** [comment]
Hello, I am currently working with this template, practicing a little and I would like to know what the root file (_app.js) is so I can configure the i18n https://www.i18next.com/overview/getting-started tool to use it as you propose, friend, could you explain to me where I can locate the configuration in the template?

**Comment by sseshaheen** [comment]
Have a look at this PR which integrates [next-intl](https://www.npmjs.com/package/next-intl) to the starter: https://github.com/medusajs/nextjs-starter-medusa/pull/456
