### ISSUE TITLE
Type error: Type 'PricedProduct[] | never[]' is not assignable to type 'Product[]'

### ISSUE THREAD

**Issue by mitulp236** [medusajs/nextjs-starter-medusa#119]
Facing issues while npm run build

Type error: Type 'PricedProduct[] | never[]' is not assignable to type 'Product[]'.
  Type 'PricedProduct[]' is not assignable to type 'Product[]'.
    Property 'beforeInsert' is missing in type 'PricedProduct' but required in type 'Product'.

**Comment by Dakai** [comment]
Same issue,don't know how to fix it, the query for products using medusaClient from @medusa/medusa-js returns the PricedProduct[] instead of Product[]

**Comment by mickeiik** [comment]
Personally I used [patch-package](https://www.npmjs.com/package/patch-package) to dirty patch the @medusajs/medusa package.

Quick walktrough:
1. Add "patch-package" as a dependency to your project using your preferred package manager
2. Install node modules if not installed already
3. Make the following edits to `@medusajs/medusa` :
- In `/node_modules/@medusajs/medusa/dist/models/product-variant.d.ts`
  - remove `private beforeInsert;` in `ProductVariant` class
- In `/node_modules/@medusajs/medusa/dist/models/product.d.ts`
  - remove `private beforeInsert;` in `Product` class
- In `/node_modules/@medusajs/medusa/dist/types/pricing.d.ts`
  - replace `export declare type PricedVariant = Partial<ProductVariant> & ProductVariantPricing;` by `export declare type PricedVariant = ProductVariant & ProductVariantPricing;`
  - replace `export declare type PricedProduct = Omit<Partial<Product>, "variants"> & {` by `export declare type PricedProduct = Omit<Product, "variants"> & {`
4. Run `npx patch-package @medusajs/medusa`. This will generate a diff between the original package and the one you just edited locally and save that in a new `patches` directory.
5. Add a `post-install` script to your `package.json` to automatically run `patch-package` and apply the patch to the node module. In `package.json` in `scripts` add `"postinstall": "patch-package"`
Alternatively you can run `npx patch-package` to apply all the patches available in `patches` the directory.
6. Lock the `@medusajs/medusa` package version for now and don't forget to remove all that when a proper fix is released in a new version.

That is a quick and dirty fix obviously.
I am not using this for production at the moment so this is at your own risks.
I didn't have any issue in my testing.
