### ISSUE TITLE
CAN WE HAVE PAYMENT INTEGRATION FOR PAYSTACK OR FLUTTERWAVE

### ISSUE THREAD

**Issue by eoluwakayode34** [medusajs/nextjs-starter-medusa#120]
I love Medusa but I am from Nigeria where Stripe and other services are not easily supported,
you need to register your company in the US to use Stripe, 
Paystack and Flutterwave are the biggest payment system in Nigeria and Africa
and integrating with these two system would mean MEDUSA is easy to use in Africa.

**Comment by kasperkristensen** [comment]
Hi @eoluwakayode34,

We aren't creating new plugins ourselves at the moment, but you can always implement your own payment plugin, or check NPM if there already exists one that fits your use case.

**Comment by mudiageo** [comment]
Check out this package https://www.npmjs.com/package/medusa-payment-paystack for payment integration with Paystack

**Comment by mudiageo** [comment]
Hello @eoluwakayode34,  
Check out this package https://www.npmjs.com/package/medusa-payment-paystack for payment integration with Paystack

**Comment by SamuelMabonga** [comment]
Has anyone yet figured out how to integrate flutterwave?
