### ISSUE TITLE
Deploy NextJs Storefront using Docker Run

### ISSUE THREAD

**Issue by quang-ng** [medusajs/nextjs-starter-medusa#122]
Hello folks,

The  Nextjs uses SSG for most pages and we need a backend server running in build time. So how we can build an image and can use it in both development and production environments. They have different backend server URL  and we only know about the backend server at run time, when we run `docker run -e NEXT_PUBLIC_MEDUSA_BACKEND_URL=backend-dev.host.com` or `docker run -e NEXT_PUBLIC_MEDUSA_BACKEND_URL=backend-prod.host.com`

**Comment by quang-ng** [comment]
Link in Discord channel: https://discord.com/channels/876835651130097704/1106152560143900724

**Comment by kasperkristensen** [comment]
Hi @quang-ng,

We don't use Docker ourselves and can't offer you support on this question. Hope you will be able to figure it out, but I will close the issue, as it is outside the scope of this project.

**Comment by GeoffreyBrunet** [comment]
bad response :(
