### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by HeinKoZin** [medusajs/nextjs-starter-medusa#126]
I have a problem when I go to the product details page.

<img width="1049" alt="image" src="https://github.com/medusajs/nextjs-starter-medusa/assets/28890199/6e3aaabd-df66-4952-9bb8-d10675d865c6">

**Comment by HeinKoZin** [comment]
This my console log.

`error - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  type: 'Error',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    transformRequest: [ null ],
    transformResponse: [ null ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.24.0'
    },
    baseURL: 'http://localhost:9000',
    raxConfig: {
      retry: 3,
      backoffType: 'exponential',
      currentRetryAttempt: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      checkRetryAfter: true,
      maxRetryAfter: 300000,
      statusCodesToRetry: [Array]
    },
    method: 'get',
    withCredentials: true,
    url: '/store/products?limit=25',
    json: true
  },
  code: 'ECONNRESET',
  status: null,
  page: '/products/[handle]'
}
`

**Comment by kasperkristensen** [comment]
Hard to debug from that message alone, the best guess would be that you have another process running on the same port as your Medusa server. You could try to use the terminal to see if you have multiple processes running, and if that is the case then either change the port that you run Medusa on or kill the other process.

Closing this as it is related to your local setup, and not directly related to Medusa or this starter.
