### ISSUE TITLE
Request for GDPR Notification Feature in Next.js Starter Medusa

### ISSUE THREAD

**Issue by ivanskodje** [medusajs/nextjs-starter-medusa#128]
As many of you may already know, hosting a website in the EU requires the provision of a GDPR notification that users must accept when their information is being collected. However, upon my initial exploration of the nextjs-starter-medusa project, I could not find any such option.

Considering this, I propose the addition of a plugin, feature, or option to incorporate a GDPR notification specifically tailored for EU e-commerce shops.

This enhancement would ensure compliance with GDPR regulations and provide a more comprehensive solution for users of Next.js Starter Medusa. Thank you for considering this request, and I look forward to your feedback and contributions to implement this feature.

**Comment by piereligio** [comment]
Honestly I implemented it very easily based off a guide on Medium for NextJS. Took about 10 minutes

**Comment by ivanskodje** [comment]
@VariableVic Does that mean "Won't Do", or does it mean that this have been added? (Since no PR or comment was issued with the d of the Issue)
