### ISSUE TITLE
Multiple errors encountered when trying to start development server

### ISSUE THREAD

**Issue by tonievictor** [medusajs/nextjs-starter-medusa#130]
When you run yarn dev or npm run dev, the app claims to build successfully. Once you try to access it on local host, it returns several errors including  "There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:"

**Comment by ivanskodje** [comment]
Did you run `yarn` to install it before trying to run `yarn dev`? 

It would be more helpful to use if you included to full logs from and included the command you used :)

**Comment by Tonie-NG** [comment]
Apparently the error is consistent with Windows environment. I had to run it on a Linux environment and it worked just fine. 

I've referenced the root issue [here](https://github.com/vercel/next.js/issues/51383).

Thanks.
