### ISSUE TITLE
Cache is not invalidated after editing a product

### ISSUE THREAD

**Issue by thephpguy** [medusajs/nextjs-starter-medusa#134]
After editing a Product, such as adding a variant or changing the description, the next cache is not invalidated and I see the old content.

The only way for me to fix this is to rebuild.

**Comment by BetoMees** [comment]
You can set no cache into [medusa-fetch](https://github.com/medusajs/nextjs-starter-medusa/blob/main/src/lib/medusa-fetch/index.ts#L14) option just add `cache: "no-cache"`
