### ISSUE TITLE
The price conversion produces NA when I change my region to Nigeria in the Storefront

### ISSUE THREAD

**Issue by tonievictor** [medusajs/nextjs-starter-medusa#136]
When I select my shipping region in the Storefront, the price of products would normally be updated to reflect the equivalent in that region's currency.

When I select Nigeria as my region, the conversion gives an output of `NGN NA`.

Note: I've already registered Nigeria as a region on my admin dashboard, I've also registered the Nigerian Naira as a currency.

**Comment by j00p34** [comment]
@Tonie-NG You have to set a value for your specific currency for the product
products-->edit variant-->pricing
