### ISSUE TITLE
Continue to delivery doesn't work

### ISSUE THREAD

**Issue by SyedYaseen** [medusajs/nextjs-starter-medusa#137]
Continue to delivery button simply refreshes screen/ brings you to top of the screen and doesn't take you to the next section.
http://localhost:8000/checkout

**Comment by HarleySalas** [comment]
`npx create-medua-app@latest`

just followed setup tutorial and can't even select delivery method.

stuck here forever...
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/38236585/0a285974-f33f-461d-b28f-d0a0fa5943fa)
