### ISSUE TITLE
[Help Wanted] After registering on the registration page & after logging in on the login page, it does not take to the account page.

### ISSUE THREAD

**Issue by ike-keith** [medusajs/nextjs-starter-medusa#146]
First of all, thank you all developers and contributors!

I deployed my storefront on Vercel following the [official MedusaJS documentation](https://docs.medusajs.com/deployments/storefront/deploying-next-on-vercel).

When I tested it, I found that when I completed the registration on the registration page and logged in on the login page, it didn't take me to the account profile page or other pages, but it stayed on the registration page or the login page, as shown in the GIF below:

![gif](https://github.com/medusajs/nextjs-starter-medusa/assets/44292757/aa45c2d2-aad6-46bc-a22e-106051a334a0)

Confirmed that the test user has completed registration in the database.

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/44292757/38251b63-d09d-46d2-8704-13561cd5a2f7)

The corresponding log from the Medusa backend:
(The IP address and storefront URL have been hidden.)
```
::ffff:ip.add.re.ss - - [19/Jul/2023:07:40:49 +0000] "GET /health HTTP/1.1" 200 2 "-" "ELB-HealthChecker/2.0"
::ffff:ip.add.re.ss - - [19/Jul/2023:07:40:49 +0000] "GET /health HTTP/1.1" 200 2 "-" "ELB-HealthChecker/2.0"
ip.add.re.ss - - [19/Jul/2023:07:40:54 +0000] "OPTIONS /store/customers HTTP/1.1" 204 0 "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:40:55 +0000] "POST /store/customers HTTP/1.1" 200 338 "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
info:    Processing customer.created which has 0 subscribers
ip.add.re.ss - - [19/Jul/2023:07:40:56 +0000] "GET /store/customers/me HTTP/1.1" 401 - "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:40:57 +0000] "GET /store/customers/me HTTP/1.1" 401 - "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:17 +0000] "OPTIONS /store/auth HTTP/1.1" 204 0 "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:18 +0000] "POST /store/auth HTTP/1.1" 200 327 "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:19 +0000] "GET /store/customers/me HTTP/1.1" 401 - "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
::ffff:ip.add.re.ss - - [19/Jul/2023:07:41:19 +0000] "GET /health HTTP/1.1" 200 2 "-" "ELB-HealthChecker/2.0"
::ffff:ip.add.re.ss - - [19/Jul/2023:07:41:19 +0000] "GET /health HTTP/1.1" 200 2 "-" "ELB-HealthChecker/2.0"
ip.add.re.ss - - [19/Jul/2023:07:41:20 +0000] "GET /store/customers/me HTTP/1.1" 401 - "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:26 +0000] "OPTIONS /store/auth HTTP/1.1" 204 0 "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:27 +0000] "POST /store/auth HTTP/1.1" 200 327 "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:27 +0000] "GET /store/customers/me HTTP/1.1" 401 - "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
ip.add.re.ss - - [19/Jul/2023:07:41:29 +0000] "GET /store/customers/me HTTP/1.1" 401 - "https://nextjs-starter-medusajs-mydomain.vercel.app/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
::ffff:ip.add.re.ss - - [19/Jul/2023:07:41:49 +0000] "GET /health HTTP/1.1" 200 2 "-" "ELB-HealthChecker/2.0"
::ffff:ip.add.re.ss - - [19/Jul/2023:07:41:49 +0000] "GET /health HTTP/1.1" 200 2 "-" "ELB-HealthChecker/2.0"
```

I don't know if the information below is helpful in figuring out what the problem is.

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/44292757/683cb5bd-98da-43c5-99ab-f8c74eee11bd)
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/44292757/1aedbb5a-9a16-4a79-9148-4c7cebacc6e0)
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/44292757/fe0d3332-8681-4aca-90b3-08887040cb3e)

I'm not a developer and don't know how to solve it, so came here for some help or tips, thanks in advance!

**Comment by ArnavK-09** [comment]
+1

**Comment by uro** [comment]
It's funny, but I am also affected by this issue. Did you find a solution @ike-keith?

Will post my investigations below:
Using medusa 1.17.2 with redis session store

I noticed there are differences in created sessions between registration and login

If we log in, the session creates with customer_id property
```json
{"cookie":{"originalMaxAge":36000000,"expires":"2023-10-28T10:48:46.364Z","secure":false,"httpOnly":true,"path":"/","sameSite":false},"customer_id":"cus_01H0DBPQGXJ8J0E5W26RCVMRYT"}
```

If we register, the session is created with jwt_store property. The getSession endpoint then returns 401 as it's not valid
```json
{"cookie":{"originalMaxAge":36000000,"expires":"2023-10-28T10:45:09.125Z","secure":false,"httpOnly":true,"path":"/","sameSite":false},"jwt_store":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6ImN1c18wMUhEU1ZWVEhYRDA2SDFUQ1A1VlNEQlYzUiIsImlhdCI6MTY5ODQ1MzkwOCwiZXhwIjoxNzAxMDQ1OTA4fQ.paeWUTHWDa5met-_JbQgbMUDA0vVqqLEWONj29CGjQ0"}
```

The session-creation logic between these two endpoints is equal, trying to find what differs

**Comment by uro** [comment]
Het @ArnavK-09 do you still need help with this? I was affected by this issue and found it happened by my overridden endpoint. The team changed how we store the sessions from JWT to simple Customer ID. You can update to ^1.17.0, and this shouldn't occur anymore.

**Comment by ArnavK-09** [comment]
> Het @ArnavK-09 do you still need help with this? I was affected by this issue and found it happened by my overridden endpoint. The team changed how we store the sessions from JWT to simple Customer ID. You can update to ^1.17.0, and this shouldn't occur anymore. 
> 
> 
> I think this issue can be closed now
> 

I was talking about this error in the official demo! It's still not working

**Comment by HeinKoZin** [comment]
+1

**Comment by stephanboersma** [comment]
+1

**Comment by sebastian-violet** [comment]
Looks like inorder to create a customer, the register endpoint has to be called with just the publishable key, and after a successful registration, the token from that response has to be used to the call to create the customer.

The signup flow in the nextjs layer misses the second part.

I added the following code in the signup flow, and this seems to work:
```js
await setAuthToken(token as string)
```

I will send out a PR to fix this issue and share the link to that PR here.

**Comment by sebastian-violet** [comment]
Looks like I do not have permission to create a pull request, so here is the simple fix as a diff:
```diff
diff --git a/src/lib/data/customer.ts b/src/lib/data/customer.ts
index 3fc7d93..a955b06 100644
--- a/src/lib/data/customer.ts
+++ b/src/lib/data/customer.ts
@@ -68,6 +68,8 @@ export async function signup(_currentState: unknown, formData: FormData) {
       password: password,
     })
 
+    await setAuthToken(token as string)
+
     const headers = {
       ...(await getAuthHeaders()),
     }
```

**Comment by sebastian-violet** [comment]
@VariableVic, @QAComet, @kasperkristensen, @sradevski, @fPolic, @olivermrbl, @shahednasser and @riqwan, as recent contributors to this repo, will you be able to create a PR with there changes?
```diff
diff --git a/src/lib/data/customer.ts b/src/lib/data/customer.ts
index 3fc7d93..a955b06 100644
--- a/src/lib/data/customer.ts
+++ b/src/lib/data/customer.ts
@@ -68,6 +68,8 @@ export async function signup(_currentState: unknown, formData: FormData) {
       password: password,
     })
 
+    await setAuthToken(token as string)
+
     const headers = {
       ...(await getAuthHeaders()),
     }
```

This fixes the Signup flow, where the JWT Token from `register customer` is made available to the subsequent `create customer` call. `getAuthHeaders` is looking for a cookie that doesn't exist, and that is why a user gets created with without an `actor_id`(Customer Id) associated with it.

Thank You in advance
