### ISSUE TITLE
Fail to load resource batch-jobs 

### ISSUE THREAD

**Issue by yasirmturk** [medusajs/nextjs-starter-medusa#167]
I have deployed backend to cpanel nodejs app. Both api and admin panel are working fine but on page load I get these errors. Any idea about what is missing here?
<img width="505" alt="Screenshot 2023-09-04 at 5 04 59 PM" src="https://github.com/medusajs/nextjs-starter-medusa/assets/306691/a87c8839-5304-410d-8be4-898b9a972f36">

**Comment by habibullah-turkmen-peacegl** [comment]
> I have deployed backend to cpanel nodejs app. Both api and admin panel are working fine but on page load I get these errors. Any idea about what is missing here? <img alt="Screenshot 2023-09-04 at 5 04 59 PM" width="505" src="https://user-images.githubusercontent.com/306691/265502843-a87c8839-5304-410d-8be4-898b9a972f36.png">

First log in to the admin panel and the errors will go away. You won't be able to access batch jobs because you aren't logged in. They are batch job and auth errors.

**Comment by habibullahturkmen** [comment]
First log in to the admin panel and the errors will go away. You won't be able to access batch jobs because you aren't logged in. They are batch jobs and auth errors.
