### ISSUE TITLE
Product Module isn't off by default

### ISSUE THREAD

**Issue by DimitriMichel** [medusajs/nextjs-starter-medusa#171]
It appears as though this cannot be deployed to Vercel even though the product module is set to false in the store config. I'm getting this error when trying to deploy. 

```
Could not resolve module: ProductModuleService. Error: Loaders for module ProductModuleService failed: 
No database clientUrl provided. Please provide the clientUrl through the PRODUCT_POSTGRES_URL or POSTGRES_URL environment variable or the options object in the initialize function.
Error occurred prerendering page "/api/categories". Read more: https://nextjs.org/docs/messages/prerender-error
--
15:34:59.153 | TypeError: Cannot set properties of undefined (setting '__definition')
15:34:59.154 | at MedusaModule.bootstrap (/vercel/path0/node_modules/@medusajs/product/node_modules/@medusajs/modules-sdk/dist/medusa-module.js:113:44)
```

**Comment by VariableVic** [comment]
Thanks for pointing this out!

Vercel will always try to build the routes in the app folder on deploy, even when you disable the module in the settings.
If you're not planning on using the serverless modules, you can safely delete or exclude the `src/app/api` folder before deploying. The API routes are only used by the serverless modules. 

If you later decide to use the modules anyway, you can always grab the files from the repo.

I'll see if I can come up with a more elegant solution for this.

**Comment by miguelcobain** [comment]
> If you're not planning on using the serverless modules, you can safely delete or exclude the src/app/api folder before deploying. The API routes are only used by the serverless modules.

I think mentioning this in the guides would be helpful.
