### ISSUE TITLE
Invalid data from seed " invalid_data"

### ISSUE THREAD

**Issue by karimhes** [medusajs/nextjs-starter-medusa#177]
# Summary

Invalid limit error when using /api/products endpoint in Medusa Next.js starter

## Details

When calling the `/api/products` endpoint with query parameters like below, I get the following error:

/api/products?limit=4&offset=4&limit=4&cart_id=cart_01HAED466QSZ2GDPEVEW6GS6SK&region_id=reg_01HABDWJ2HARHHRZRRJMNGERRD
{"type":"invalid_data","message":"limit must be a number conforming to the specified constraints"}

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/10757258/b194a844-7283-4cf1-ab5c-8c4f401f4e9e)

It seems to occur when both `limit` and `offset` are provided in the query string. 

The products were added by sample data and failed to load.

## Reproduction

1. Clone Medusa Next.js starter 
2. Run `medusa develop`
3. Go to `/api/products?limit=4&offset=4&limit=4&cart_id=...`
4. See the error

## Expected Behavior 

It should validate and parse `limit` and `offset` parameters correctly.

If both are provided, it should use the last `limit` value specified.

## Environment

- Medusa Next.js starter 
- "name": "medusa-next",
- "version": "1.0.3",
- OS: Ubuntu

Let me know if any other details would be helpful!

Also you can the latest build admin dashboard seems to fail at loading sample products.

**Comment by monstajoe2002** [comment]
I have the same problem when I try to associate an email with a cart
