### ISSUE TITLE
Issue with 404

### ISSUE THREAD

**Issue by emeczku** [medusajs/nextjs-starter-medusa#191]
If the backend is available and we try to navigate to a URL that is not available, we get the following error:

Unhandled Runtime Error
Error: Cannot read properties of undefined (reading 'name')

**Comment by luluhoc** [comment]
This is an error in starter if category doesn't exists

file app/(main)/[...category]/page.tsx
`export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { product_categories } = await getCategoryByHandle(
    params.category
  ).catch((err) => {
    notFound()
  })

  const category = product_categories[0]

  return {
    title: `${category?.name} | Acme Store`,
    description: `${category?.name} category`,
  }
}`

**Comment by luluhoc** [comment]
Check out my pull

https://github.com/medusajs/nextjs-starter-medusa/pull/196
