### ISSUE TITLE
Error with fresh server + Medusa Storefront 2.0

### ISSUE THREAD

**Issue by ensidialabs** [medusajs/nextjs-starter-medusa#203]
Import trace for requested module:
./node_modules/.pnpm/@medusajs+utils@1.11.0_pg@8.11.0/node_modules/@medusajs/utils/dist/common/get-config-file.js
./node_modules/.pnpm/@medusajs+utils@1.11.0_pg@8.11.0/node_modules/@medusajs/utils/dist/common/index.js
./node_modules/.pnpm/@medusajs+utils@1.11.0_pg@8.11.0/node_modules/@medusajs/utils/dist/feature-flags/utils/flag-router.js
./node_modules/.pnpm/@medusajs+utils@1.11.0_pg@8.11.0/node_modules/@medusajs/utils/dist/feature-flags/utils/index.js
./node_modules/.pnpm/@medusajs+utils@1.11.0_pg@8.11.0/node_modules/@medusajs/utils/dist/feature-flags/index.js
./src/lib/data/index.ts
./src/app/(main)/page.tsx

./node_modules/.pnpm/awilix@8.0.1/node_modules/awilix/lib/load-module-native.js
Critical dependency: the request of a dependency is an expression

Clean installation. And here is the error.

**Comment by bhaveshselarka** [comment]
https://github.com/medusajs/nextjs-starter-medusa/issues/207

**Comment by ensidialabs** [comment]
Checked. Everything seems ok. I will look again tomorrow.
