### ISSUE TITLE
First load of a product page takes 7 sec

### ISSUE THREAD

**Issue by nfzv** [medusajs/nextjs-starter-medusa#209]
I appreciate the contributors behind these amazing projects!
I seem to have a weird issue, would be glad if someone could guide me on the debugging.
Apparently the first product page takes too long, I assume the database fetch. Let's put away the database problems first, I would appreciate any guides on making so that clicking on a product, at least loads the page first and loads whatever it needs later. Because when I click the first time, ther is no any visual feedback at least for 4 seconds. I might be wrong but I believe, most of the pages aren't well structured for initial server-side loading.

Open to your ideas.

### Here is the networks tab
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/51998193/dd160b53-9fd3-49ac-971b-54fac76701b3)

Desired behaviour is to meet these [web vitals](https://web.dev/articles/vitals#core_web_vitals)

**Comment by aidensgithub** [comment]
Some more stats
---
### Here is the performance insight
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/51998193/b0df4e44-fee7-44d1-9d05-150457d14428)

### Initial page loading request (light blue) states 14 seconds of wating
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/51998193/0ad8dbb0-0363-4378-821f-6df923666a6b)
