### ISSUE TITLE
Error deploying latest version on Vercel

### ISSUE THREAD

**Issue by jwoa** [medusajs/nextjs-starter-medusa#210]
Hey,

Thanks for the great template and Medusa in general! Everything works great locally but when trying to deploy the latest frontend/storefront on Vercel I keep running into an unexpected JSON error.

![Screenshot 2023-11-26 at 9 18 42 AM](https://github.com/medusajs/nextjs-starter-medusa/assets/14006716/48232940-fce0-4e29-b469-55396fedf3fa)

I've tried both manually and with the deploy button and always end up here. Any suggestions or fixes?

**Comment by VariableVic** [comment]
Hey @jwoa, this is error usually means the storefront can't access the backend properly. Have you set the `STORE_CORS` env var on your server to include your Vercel storefront domain?

**Comment by jwoa** [comment]
Hey @VariableVic, tried that as well but unfortunately got the same error. Could it be a chicken and egg scenario where there's no domain because the site can't initially be provisioned in vercel?

<img width="942" alt="Screenshot 2023-11-27 at 7 46 43 PM" src="https://github.com/medusajs/nextjs-starter-medusa/assets/14006716/22307b4c-2865-472c-a94e-9b4d80026675">

**Comment by oguzergul** [comment]
Hey @VariableVic, I'm encountering the same issue with my Vercel starter. While my backend service deployed on Render is functioning correctly, I'm having trouble deploying the storefront on Vercel.

**Comment by estebankra** [comment]
I've encountered the same error. I can reproduce it in my local environment too when the backend is offline.

I found that the issue might be related to this specific line of code.
![Screenshot from 2023-11-28 21-37-02](https://github.com/medusajs/nextjs-starter-medusa/assets/35118529/0392bf2b-5d0b-48fc-95df-256bb1d88ff7)

Upon commenting out that line, I was able to successfully deploy the changes on Vercel. Does anyone have any idea of why this line is causing deployment issues?

**Comment by estebankra** [comment]
I found that the error comes from this 'fetch' operation within the 'medusaRequest'
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/35118529/bbf1201a-9ff4-467e-83b3-d9f55f9af028)

**Comment by jwoa** [comment]
@estebankra Thanks for that! It solved the Vercel deployment issue. Just have to sort the products loading now/CORS

**Comment by VariableVic** [comment]
Thanks for the info @estebankra! I can't reproduce this issue locally, even with a fresh install with no collections/products in it. It just returns an empty array and displays no collections on the homepage (like it should). I'll spend some more time on debugging this today.

Just to make sure, have you set the `NEXT_PUBLIC_MEDUSA_BACKEND_URL` env variable in Vercel? This should be your backend url without trailing `/` or `/store`.

**Comment by estebankra** [comment]
@jwoa Check out what @VariableVic said in his comment

"Just to make sure, have you set the NEXT_PUBLIC_MEDUSA_BACKEND_URL env variable in Vercel? This should be your backend url **without trailing / or /store.**"

It looks like I first put my URL in my environment by including `/` at the end like `https://backend.example.com/`, because now that I checked my env and undo my changes, the deploy works without needing to comment any lines.

**Comment by hmmhmmhm** [comment]
> Thanks for the info @estebankra! I can't reproduce this issue locally, even with a fresh install with no collections/products in it. It just returns an empty array and displays no collections on the homepage (like it should). I'll spend some more time on debugging this today.
> 
> Just to make sure, have you set the `NEXT_PUBLIC_MEDUSA_BACKEND_URL` env variable in Vercel? This should be your backend url without trailing `/` or `/store`.

This seems to be the problem. I succeeded by removing the / at the end of `NEXT_PUBLIC_MEDUSA_BACKEND_URL`.

**Comment by pmltechpile** [comment]
Getting the same error but my NEXT_PUBLIC_MEDUSA_BACKEND_URL does not have the trailing / at the end. Not sure what else it could be

**Comment by Dalvae** [comment]
I'm having the same error as @pmltechpile I bypass the deploy error by commenting the line like @estebankra  says, but that's not the way to solve it, because its not showing the products on the main page. My CORS are god, I can tell because I can get products from the products sections. 

I got some intuitions that there is problem with categories or something.

**Comment by VariableVic** [comment]
@pmltechpile @Dalvae The `unexpected token < ...` error usually means Vercel couldn't reach the Medusa backend server properly. If there was an issue with your collections, Medusa would most likely throw a different error or just return an empty array. Can you check your Medusa server logs when you run the Vercel deployment and see if the request ever actually reaches the server?

**Comment by Dalvae** [comment]
@VariableVic I tried a redeploy and nothing reaches the server 

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/101679648/07483d84-76f3-45ad-bc77-8c76b99b4662)

**Comment by SkullXA** [comment]
I'm getting the same issue, how did you end up solving it?

**Comment by jwoa** [comment]
> I'm getting the same issue, how did you end up solving it? 

I didn't. Ended up abandoning it and switching to Shopify but I'm to exploring Medusa again. Will try another install this weekend and post a follow up

**Comment by SkullXA** [comment]
> > I'm getting the same issue, how did you end up solving it? 
> 
> I didn't. Ended up abandoning it and switching to Shopify but I'm to exploring Medusa again. Will try another install this weekend and post a follow up 

Lmao... never give up.. Medusa is 500% more powerful than Shopify. I love the .tsx file structure, the next js, it's incredible I can single handle create a 150,000$ website myself. You know it was such a simple mistake, it's because i put / in the end of the url. For example in your env file you put "domain.com" however never put "domain.com/" that's all it was. And everything is working now

**Comment by jwoa** [comment]
> > > I'm getting the same issue, how did you end up solving it? 
> > 
> > I didn't. Ended up abandoning it and switching to Shopify but I'm to exploring Medusa again. Will try another install this weekend and post a follow up 
> 
> Lmao... never give up.. Medusa is 500% more powerful than Shopify. I love the .tsx file structure, the next js, it's incredible I can single handle create a 150,000$ website myself. You know it was such a simple mistake, it's because i put / in the end of the url. For example in your env file you put "domain.com" however never put "domain.com/" that's all it was. And everything is working now 

lol I'm down to give it another go, younger me was just extremely impatient and wanted something not so fragile but you're right the flexibility of Medusa is what lured me in
