### ISSUE TITLE
Unable to complete payment using stripe

### ISSUE THREAD

**Issue by chrislaai** [medusajs/nextjs-starter-medusa#215]
I'm using the latest code and when I click on the "Place order" button nothing happens.
<img width="1820" alt="image" src="https://github.com/medusajs/nextjs-starter-medusa/assets/134155599/da7ddb31-2cda-4d0e-b4ea-e9f345e892b3">

**Comment by InternetOscar** [comment]
I'm getting the same problem. No console outputs or errors generated in the terminal.

**Comment by VariableVic** [comment]
Should be fixed in https://github.com/medusajs/nextjs-starter-medusa/pull/218. Lmk it solves your issues!

**Comment by tabilzad** [comment]
> Should be fixed in #218. Lmk if it solves your issues!
Works flawlessly for me. Thanks!
