### ISSUE TITLE
[Feature Request] Add a category filter and keep the collections using the checkbox option

### ISSUE THREAD

**Issue by chrislaai** [medusajs/nextjs-starter-medusa#220]
Due to the use of categories, we should add a category filter to the "store" page. After turning on the category filter, should we consider keeping "Collections" as a 'checkbox' option? If using 'radio', the situation faced is that after selecting the collection and category, Collections cannot be deselected. It is acceptable to use the 'radio' type option for product categories because customers will always choose a category of products to browse. Between collections and categories, it seems more reasonable to keep "Collections" as the 'checkbox' option.
<img width="273" alt="image" src="https://github.com/medusajs/nextjs-starter-medusa/assets/134155599/5536d5b4-7d13-4af5-9c2b-dac49c43e6f6">

**Comment by kb-0912** [comment]
@VariableVic may I know is there any update with this?

**Comment by kb-0912** [comment]
> Hey guys,
> I'd love to add proper product filtering to the Starter at some point, but we're currently not planning any changes to this component.
> I'd be happy to accept a PR for this if anyone is up to it.

The previous version had Collection Filter but now it's removed :( I'm trying to add it again by myself but it's does not work

**Comment by TimchaStudio** [comment]
Is there any progress on this issue?
