### ISSUE TITLE
 zero-decimal currencies are beeing divided by 100

### ISSUE THREAD

**Issue by Dalvae** [medusajs/nextjs-starter-medusa#224]
According to the documentation, CLP (Chilean Peso) is classified as a zero-decimal currency. However, in our application, CLP values are being divided by 100, which is inconsistent with how zero-decimal currencies should be handled.
Description

We are experiencing an issue where prices in CLP are incorrectly processed as if they were decimal-based currencies. This results in all our CLP prices being divided by 100, leading to incorrect price calculations and displays in our application.
Expected Behavior

For zero-decimal currencies like CLP, the price should not be divided by 100. The amount should be treated as the smallest unit of the currency without any conversion.
Current Behavior

All amounts in CLP are divided by 100, which is the standard handling for decimal-based currencies. This leads to incorrect price representations, significantly impacting the user experience and pricing accuracy in our application.
Steps to Reproduce

    Set the application currency to CLP.
    Input or retrieve a product price (e.g., 1000 CLP).
    Observe the price being processed and displayed as 10 CLP.

![2023-12-16-18-53-55](https://github.com/medusajs/nextjs-starter-medusa/assets/101679648/0ca1bb14-4098-49bf-822a-7af2d4537909)
![2023-12-16-18-51-57](https://github.com/medusajs/nextjs-starter-medusa/assets/101679648/170c2739-54cd-4f86-b406-8b810171e6f7)

**Comment by VariableVic** [comment]
Thanks for pointing this out. It's actually an issue in our `medusa-react` package, [this helper](https://github.com/medusajs/medusa/blob/a3460e5a1aacecc1b51f0f5eb5e913fd3aecc8d2/packages/medusa-react/src/helpers/index.ts#L129) specifically. Please create an issue on our main repo so the core team will see it.

I'm currently working on an update for the starter that doesn't rely as much on `medusa-react`, and this specific list will be directly editable in the Starter project. I'll add CLP to it right away!
