### ISSUE TITLE
Fails to compile, cant deploy to Vercel either

### ISSUE THREAD

**Issue by Kainkainkain** [medusajs/nextjs-starter-medusa#225]
It seems to have a problem finding '@medusajs/types'
Indeed if I look at files referring to that, they are red underlined. 

run dev works fine. 

pnpm run build

> medusa-next@1.0.3 build
> next build

next.config.js {
  "experimental": {
    "serverComponentsExternalPackages": [
      "@medusajs/product",
      "@medusajs/modules-sdk"
    ]
  },
  "reactStrictMode": true,
  "images": {
    "remotePatterns": [
      {
        "protocol": "http",
        "hostname": "localhost"
      } 
    ]
  },
  "env": {}
}
   ▲ Next.js 14.0.4
   - Environments: .env

 ✓ Creating an optimized production build    
 ✓ Compiled successfully

./src/lib/context/checkout-context.tsx
238:6  Warning: React Hook useEffect has a missing dependency: 'initPayment'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/modules/layout/components/footer-nav/index.tsx
23:16  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
135:18  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
135:18  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  ...Failed to compile.

./src/lib/util/filter-products-by-status.ts:1:28
Type error: Cannot find module '@medusajs/types/dist/product/common' or its corresponding type declarations.

> 1 | import { ProductDTO } from "@medusajs/types/dist/product/common"
    |                            ^
  2 |
  3 | export default function filterProductsByStatus(
  4 |   products: ProductDTO[],

**Comment by Kainkainkain** [comment]
pnpm i @medusajs/types fixed that issue - but I don't know why it wasn't already in package and why npm dev works. 

next issue was same thing- missing package  @radix-ui/react-accordion. Also pnpm i  @radix-ui/react-accordion   to solve.

**Comment by TimchaStudio** [comment]
Is there any progress on this issue?
