### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by andreasoikon** [medusajs/nextjs-starter-medusa#237]
I just tried to access the demo page --> https://next.medusajs.com/

And it is not working.

I get the error mentioned below.
`Application error: a server-side exception has occurred (see the server logs for more information). Digest: 1283094609`

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/26843211/9ccb255d-73e7-41f5-882e-464571153b6e)

**Comment by OmarMHawash** [comment]
+1, still not working

**Comment by woniuxingdong** [comment]
I can access the demo as of speaking. Try again.

**Comment by OmarMHawash** [comment]
Yes its working now

**Comment by VariableVic** [comment]
Thanks for the heads up! Redis ran out of memory. We've bumped the Heroku plan, so it has some more headroom now.  Shouldn't happen again.
