### ISSUE TITLE
Too Many Redirects 307

### ISSUE THREAD

**Issue by ahgsql** [medusajs/nextjs-starter-medusa#238]
After installing storefront, cant access the webpage, 

i checked every step more than twice, but everytime, even i install storefront freshly, i got 307 Too many redirect error on localhost:8000

**Comment by msiviero** [comment]
Same here

**Comment by msiviero** [comment]
Turned out, at least for me, that the default country in src/middleware.ts is 'us' and I didn't configure a region with it. Changing the default country made it work

**Comment by VariableVic** [comment]
Yeah, I should point this out in Readme! Thanks for bringing it up

**Comment by ahgsql** [comment]
After changing region in middleware.ts, i was able to fix the problem too.

**Comment by AlbertoCanoD** [comment]
I have a doubt, I am only going to use the spanish region, my clients can only come from there, is there any way to simplify everything, it is giving me a lot of 307 problems even if I change the hardcoded region or the environment variable, I am deploying the front end in Vercel. Thank you very much!!!

@VariableVic @msiviero

**Comment by mehdinourollah** [comment]
After changing default value to "de" I get internal server error as follow:
```
 ⨯ node_modules\@medusajs\medusa-js\node_modules\axios\lib\core\createError.js (16:14) @ createError
 ⨯ Error: Request failed with status code 500
    at IncomingMessage.emit (node:events:529:35)
null
```

any idea ?
