### ISSUE TITLE
How do you keep your store up-to-date with this starter?

### ISSUE THREAD

**Issue by max-arias** [medusajs/nextjs-starter-medusa#240]
Surely cloning and merging files isn't the best way. Any tips?

**Comment by mohdziyadc** [comment]
Yeah please give us a reply. I already have a custom storefront built using the earlier template, how do I now add the increased performance given by this new update to my already existing storefront by keeping the changes that I have did in my current storefront? I tried adding a new remote repo in my project and set its url to this repo. Fetched from this repo and tried to merge the main branch to my repo. But then I have to manually resolve the merge conflicts and it becomes tedious. Also I lose my change which I have introduced. What to do?

**Comment by VariableVic** [comment]
Hey guys,

The app architecture has changed quite a lot. There's no one-size-fits-all solution to upgrade atm.
So depending on your current setup, it might take quite a bit of refactoring.

Depending on the type of customizations you have done to the storefront, it could be easier to clone the new starter and add your customizations back in. If it's mostly styling this shouldn't be too difficult.

I'm currently writing an article explaining the new setup and patterns. That should give you some pointers on how to upgrade.

I'll post a link here when it's up!

**Comment by max-arias** [comment]
Appreciate your work here @VariableVic ! I'll keep an eye out for the article.

**Comment by VariableVic** [comment]
Article is out guys, [here](https://twitter.com/medusajs/status/1754840211610382446) ya go

**Comment by cmario92** [comment]
> Article is out guys, [here](https://twitter.com/medusajs/status/1754840211610382446) ya go

not sure this article provides an answer to this question, right?

**Comment by VariableVic** [comment]
> not sure this article provides an answer to this question, right?

It's not an upgrade guide, but I was hoping it would shed some light on the new patterns, making it easier to upgrade your own instance.
