### ISSUE TITLE
Store front: Module not found: Package path ./lib/core/settle is not exported from package

### ISSUE THREAD

**Issue by venkatkotni** [medusajs/nextjs-starter-medusa#266]
while doing "yarn dev" on initial setup of storefront 
I'm getting the below error

Module not found: Package path ./lib/core/settle is not exported from package D:\IBM Cloud\new-medusa\medusa-storefront\node_modules\axios (see exports field in D:\IBM Cloud\new-medusa\medusa-storefront\node_modules\axios\package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/lib/config.ts
./src/lib/data/index.ts
./src/app/actions.ts
./node_modules/next/dist/build/webpack/loaders/next-flight-action-entry-loader.js?actions=%5B%5B%22D%3A%5C%5CIBM%20Cloud%5C%5Cnew-medusa%5C%5Cmedusa-storefront%5C%5Csrc%5C%5Capp%5C%5Cactions.ts%22%2C%5B%22resetOnboardingState%22%2C%22updateRegion%22%5D%5D%5D&__client_imported__=true!

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/79835569/8a334679-dfb5-4049-8433-14afce83e6bb)

**Comment by VariableVic** [comment]
Looks like this was caused by an Axios version mismatch between the fetch adapter and our JS client. I've removed the adapter for now as it's not crucial. Should be solved with the linked PR. Let me know if you're still experiencing issues after this!
