### ISSUE TITLE
Slow API fetch, both in dev and prod

### ISSUE THREAD

**Issue by crnls** [medusajs/nextjs-starter-medusa#280]
The last few days I have been trying to fix extremely slow API fetch issues with my Medusa store. I have tried many obvious solutions, but so far without success. Screenshots below with logs, there are no console errors. Add to cart often takes +6 seconds, simple product pages 2-4 seconds.

Notes:

- Locally, with external DB, API is also slow
- Admin API is fast
- Backend at Heroku (https://dev.wantsandneeds.nl/)
- Admin & Storefront hosted at Vercel (Vercel functions now build at Frankfurt server) (https://admin.wantsandneeds.nl/  & https://wantsandneeds.nl/)
- Database at Supabase (Frankfurt, closest to traffic (Netherlands))
- Tested everything also in clean install, also slow fetch there. 
- Tested several DB providers (AWS RDS, multiple Supabase servers etc)
- Cart interactions are especially slow

Screenshots:
![Scherm­afbeelding 2024-02-26 om 14 11 07](https://github.com/medusajs/nextjs-starter-medusa/assets/18337971/3463663d-98bb-460b-9636-a0b5bc97d72d)
![Scherm­afbeelding 2024-02-26 om 14 05 45](https://github.com/medusajs/nextjs-starter-medusa/assets/18337971/ba9fe470-fdee-42c6-bdf3-48a1ddbaf35d)
![Scherm­afbeelding 2024-02-26 om 14 05 35](https://github.com/medusajs/nextjs-starter-medusa/assets/18337971/32fe9233-8d85-4c8d-8693-366e5486f02d)
![Scherm­afbeelding 2024-02-26 om 14 05 02](https://github.com/medusajs/nextjs-starter-medusa/assets/18337971/be4712c8-d8ca-469e-9a0d-43c0bdaf5f01)

**Comment by bqst** [comment]
Since the switch to the new starter pack and server actions, I've been facing the same issue. The actions, especially the 'add to cart' one, now take a significantly longer time (~2 sec) with the same backend.

**Comment by VariableVic** [comment]
Is it just as bad when you interact with the server directly? E.g.

```curl
curl -X POST '{backend_url}/store/carts/{id}/line-items' \
-H 'Content-Type: application/json' \
--data-raw '{
    "variant_id": "{variant_id}",
    "quantity": 1
}'
``` 
I'm running the same setup for next.medusajs.com. The only difference is that I host Redis and Postgres on Heroku instead of Supabase. So that might be the bottleneck here. 

Still weird, since you tried several DB providers. Really hard to tell what's causing this bad performance.

**Comment by dsijakovski98** [comment]
Having the same issue, very slow responses when going through the SDK. Maybe it will be faster using regular API calls to the server directly, tho haven't tried it out yet

**Comment by crnls** [comment]
Never was able to solve this, might try at a later point if caching some stuff with vercel improves load times

Groet,
Martijn van der Pas

Op 7 jun 2024 om 13:53 heeft dsijakovski98 ***@***.***> het volgende geschreven:

﻿

Having the same issue, very slow responses when going through the SDK. Maybe it will be faster using regular API calls to the server directly, tho haven't tried it out yet

**Comment by 100tomtomas100** [comment]
I have the same issue the store front with sample setup loads very slow and in dev mode its unbearable :(

**Comment by 100tomtomas100** [comment]
@dsijakovski98  isnt redis supposed to cache the database and it shouldnt matter if supabase is underperforming? 
I am lost!

**Comment by dsijakovski98** [comment]
I dont think it caches the database, it just implements resource/computation caching as I understood it. It could be just a speed up due to the fact that it doesn't have to make network requests to remote DBs, but Im with you on that it shouldn't matter that much

**Comment by 100tomtomas100** [comment]
I have hosted supabase myself and added the backend and admin in the same place and now the speed is decent. It could be a little faster but everything is happening way faster than before.
