### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by mfaeezshabbir** [medusajs/nextjs-starter-medusa#288]
I am trying to access the storefront of medusa app but i end up getting this error every time, could you please help me

![image](https://github.com/medusajs/nextjs-starter-medusa/assets/74614920/301d35b0-5c88-42e8-8c43-070bb5108bb2)

**Comment by VariableVic** [comment]
Hey @mfaeezshabbir, is you Medusa server running on localhost:9000? If it's running on a different port or domain, make sure to update the `NEXT_PUBLIC_MEDUSA_BACKEND_URL` env variable.

**Comment by mfaeezshabbir** [comment]
> Hey @mfaeezshabbir, is you Medusa server running on localhost:9000? If it's running on a different port or domain, make sure to update the `NEXT_PUBLIC_MEDUSA_BACKEND_URL` env variable. 

Yes it was on port 9000 but this error is from the storefront

**Comment by wahidbabar** [comment]
facing same issue @mfaeezshabbir @VariableVic Medusa backend is running on PORT: 7001, changed it in frontend .env, still giving same error

**Comment by lacymorrow** [comment]
The issue is most likely a CORS issue on the backend (dealt with it in production today).

Make sure the STORE_CORS variable is being set properly in your env and `medusa-config.js`

**Comment by reiser** [comment]
pretty sure its caused by wrong config pointing admin to backend:
`NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:7001` 
it should be on local
`NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:9000`

**Comment by maacaron** [comment]
I was facing the same problem with a fresh project. And while searching for a solution I looked into medusa config - there are `process.env.XYZ` vars. And I forgot to export them via console. After `export $(grep -v '^#' .env.local | xargs)` in storefront catalog it works like a charm.
