### ISSUE TITLE
MeiliSearch Instantsearch RefinementList is not working

### ISSUE THREAD

**Issue by mhernesniemi** [medusajs/nextjs-starter-medusa#289]
Problem:

> Error: MeiliSearchCommunicationError: Unknown field `facetsDistribution`: expected one of `q`, `vector`, `hybrid`, `offset`, `limit`, `page`, `hitsPerPage`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `showMatchesPosition`, `showRankingScore`, `showRankingScoreDetails`, `filter`, `sort`, `facets`, `highlightPreTag`, `highlightPostTag`, `cropMarker`, `matchingStrategy`, `attributesToSearchOn`

Fix:

Update to  "@meilisearch/instant-meilisearch": "^0.17.0"

and change search-client.ts line 8:

`export const { searchClient } = instantMeiliSearch(endpoint, apiKey)`

**Comment by VariableVic** [comment]
Nice catch, happy to accept a PR with your fix!

**Comment by eveyrat** [comment]
See PR #360
