### ISSUE TITLE
Medusa client or Nextjs caching bearer token between requests to backend for different user sessions

### ISSUE THREAD

**Issue by stf9** [medusajs/nextjs-starter-medusa#292]
I ran into an issue where guest user checkouts were pulling the customer ID from the last person to log into our store in production mode, causing orders to get attributed to the wrong customer and have the wrong email. It would only happen rarely in development mode. Maybe I have something misconfigured that's causing it to remember the bearer token.

**Problem:**
The cart data sent to the backend when updating a cart during guest checkout does not include a customer ID, but after the cart gets updated it is returning the cart with the customer ID of the last person to log into the store. 
After hours of debugging I narrowed it down to either the medusa client or nextjs caching the bearer token sent from the store to the backend, and the backend seems to remember which bearer token is associated with which user.

Reading store API documentation it seems that this is the intended behavior:

> When using Medusa's JS or Medusa React clients, the cookie is automatically attached to subsequent requests.
> https://docs.medusajs.com/api/store#auth_postauth
> 

**To reproduce the issue:** 
It only consistently happened to me after running `yarn build && yarn start`
After that, create a cart as a guest user and continue to checkout and enter the address information. 
In a private tab or separate browser, log in as a store user. 
After this, editing the previous guest cart address or any guest carts would pull the e-mail address from the last logged in user, and any orders created were associated with this customer.
I confirmed this happens on next.medusajs.com

**Fix:**
Set the authorization header to empty in getMedusaHeaders if the jwt token is not set in a cookie in `src/lib/data/index.ts`
```
const getMedusaHeaders = (tags: string[] = []) => {
  const headers = {
    next: {
      tags,
    },
  } as Record<string, any>

  const token = cookies().get("_medusa_jwt")?.value

  if (token) {
    headers.authorization = `Bearer ${token}`
  } else {
    headers.authorization = ''
  }

  return headers
}
```

I'm not too sure if this is the correct way to do it but it seems to work.

**Comment by VariableVic** [comment]
LGTM, I've pushed your suggested change. Thanks for looking into this!
