### ISSUE TITLE
Paypal Live Mode does not work

### ISSUE THREAD

**Issue by rkmcdonnell** [medusajs/nextjs-starter-medusa#307]
I am getting errors when using Paypal as a payment method with my live Paypal credentials.  For some reason, the sandbox keys work perfectly.  I've triple checked the accuracy of the live keys.  Every time I get an error in my deployed front end as follows:

Error: An error occurred in initiatePayment:
An error occurred while requesting Paypal API after 2 attempts.
    at n (/var/task/.next/server/chunks/720.js:1:30107)
    at /var/task/.next/server/chunks/720.js:1:15877
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async b (/var/task/.next/server/chunks/389.js:1:24439)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:406
    at async rm (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:5703)
    at async rD (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:22546)
    at async J (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:25253)
    at async Y.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1025)
    at async rZ.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:507)

Appears to be similar to this issue on the main medusa backend repo: https://github.com/medusajs/medusa/issues/6714.  Not sure whether it's truly a medusaJS issue or a result of something passed from the storefront.

I also thought it could be due to the bug that is underlying this PR for the docs on the main Medusa repo: https://github.com/medusajs/medusa/pull/6975#issuecomment-2042036716.  I manually changed my own implementation to use the proper PayPal ClientId within the <PayPalScriptProvider> wrapper, but this does not appear to have fixed the issue (although it does seem like something separate that should be fixed in the Storefront).  

Has anyone experienced this or similar issues?  Has anyone actually gotten Paypal payments to work in live mode using the NextJS starter storefront and the Medusa Paypal plugin?

**Comment by yunfengsay** [comment]
same error too

**Comment by powerttt** [comment]
same error too

**Comment by powerttt** [comment]
same error too

**Comment by powerttt** [comment]
same error too

**Comment by powerttt** [comment]
About paypal live failure solution
The problem comes from the judgment of `PAYPAL_SANDBOX` in `env`. You only need to set it to empty to handle the payment problem.

**Comment by mythical0beast** [comment]
thank you very much for that it worked

**Comment by mythical0beast** [comment]
thank you very much for that

**Comment by VariableVic** [comment]
Thanks for the solution @powerttt! Gonna close this thread now.

**Comment by mythical0beast** [comment]
hey it didnt end up working for me i still have problem 
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/144207147/ed80d00a-1106-423f-9a7d-7fde71590380)
even when passing as undefined

**Comment by VariableVic** [comment]
@mythical0beast have you tried setting `sandbox: false`?

**Comment by mythical0beast** [comment]
yes 

> @mythical0beast have you tried setting `sandbox: false`?

yes and as undefined still opens as sandbox as seen in link for a dash of a second 
![image](https://github.com/medusajs/nextjs-starter-medusa/assets/144207147/f9f9cb5f-9161-4e27-9bdd-2f57256db8d2)

**Comment by zvikachu** [comment]
I am still getting the sandbox url after trying @powerttt solution
