### ISSUE TITLE
NEXT_PUBLIC_MEDUSA_BACKEND_URL- Why would we expose our backend url to the client?

### ISSUE THREAD

**Issue by sschweimler** [medusajs/nextjs-starter-medusa#344]
Is there a specific reason why the backend url in .env.template is exposed to the client by using NEXT_PUBLIC? 
I think it's a bad idea because it makes the backend visible for potential attackers. If we need to access backend data on the client side, then we should use route handlers or server actions.

**Comment by Deroswent** [comment]
Totally supportive. This is a very bad idea.  

But since this starter is very buggy, and is basically the starter from version 1, with minimal changes, I hope the developers will completely change it for version 2, where they will fix it.

**Comment by VariableVic** [comment]
This is not (longer) needed and the variable has been renamed to `MEDUSA_BACKEND_URL`. Make sure to change the env variable key locally when pulling the latest changes.
