### ISSUE TITLE
Trying to run GHA e2e tests -> 401 Unauthorized -> Timeout

### ISSUE THREAD

**Issue by haf** [medusajs/nextjs-starter-medusa#359]
Hey there,

Thank you for providing this starter template!

I'm trying the GHA workflow, but after the server has started, the tests are grey-failing with 401 Unauthorized / timeouts.

I've noticed that the CI hasn't run on this repo in three months, and the previous logs are gone. Also the actions use npx assuming the latest version (non-repeatable build) of the medusa CLI so perhaps something's changed in the mean time?

Here's a gist complete with logs and the e2e workflow (very lightly modified to support yarn v4 by using corepack) https://gist.github.com/haf/b5447279a114b046d8a75c43f46a7934

Since the e2e tests are creating their own backend, I presume whatever changes I've made to my backend don't matter? I haven't yet updated the e2e tests since I haven't been able to make them run.

<img width="1060" alt="Screenshot 2024-08-24 at 23 05 00" src="https://github.com/user-attachments/assets/e02ca896-7fdf-4b7d-80a8-1d50655b48ec">
// snip
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/7b870ef5-b185-43dd-91f8-319612a829ee">

**Comment by VariableVic** [comment]
Hey @haf,

The E2E test suite was developed for V1 and is not yet updated for V2. We removed it for the time being, might update it and add it back in later as a separate project. Closing this for now.
