### ISSUE TITLE
nextjs-starter

### ISSUE THREAD

**Issue by Tech-dev-coder** [medusajs/nextjs-starter-medusa#384]
![Screenshot from 2024-10-24 17-15-36](https://github.com/user-attachments/assets/ca8e6cc5-d98a-4c30-8744-984500dd1caa)

product-rail not working in home page.

**Comment by Tech-dev-coder** [comment]
![Screenshot from 2024-10-24 17-27-16](https://github.com/user-attachments/assets/cfdf4f31-54c6-459b-8c50-68d8bc972931)
![Screenshot from 2024-10-24 17-27-30](https://github.com/user-attachments/assets/c0c2e070-738c-4052-af4e-46821714975b)

Recent orders / any order are not  showing.

**Comment by VariableVic** [comment]
1. Did you create any product collections? This component lists product collections, so for the rail to show up you need to create one first.
2. This is a known issue with 2.0 - cart updates are not properly linked to logged in customers. We're currently working on this.

**Comment by Tech-dev-coder** [comment]
Yes, I created products in the collection, but none of them are showing.

**Comment by inf-edu** [comment]
Had the same problem. Solved it by setting pageParam to 0 in getCollectionsWithProducts from collection.ts :

```
const { response } = await getProductsList({
       pageParam: 0, // add this parameter
      queryParams: { collection_id: collectionIds },
      countryCode,
    })
```

**Comment by Tech-dev-coder** [comment]
Yes, I added it, but it doesn't make any changes. I want to display the products in the product rail on the storefront home page.
 medusa-storefront/src/modules/home/components/featured-products/product-rail/index.tsx

**Comment by chillpilllike** [comment]
Any fix for this? I am facing the same issue. Please help

**Comment by chillpilllike** [comment]
> Had the same problem. Solved it by setting pageParam to 0 in getCollectionsWithProducts from collection.ts :
> 
> ```
> const { response } = await getProductsList({
>        pageParam: 0, // add this parameter
>       queryParams: { collection_id: collectionIds },
>       countryCode,
>     })
> ```

This fixed the issue for me, thanks

**Comment by Tech-dev-coder** [comment]
> > Had the same problem. Solved it by setting pageParam to 0 in getCollectionsWithProducts from collection.ts :
> > ```
> > const { response } = await getProductsList({
> >        pageParam: 0, // add this parameter
> >       queryParams: { collection_id: collectionIds },
> >       countryCode,
> >     })
> > ```
> 
> This fixed the issue for me, thanks
is this solved issue

**Comment by mhayta** [comment]
> Had the same problem. Solved it by setting pageParam to 0 in getCollectionsWithProducts from collection.ts :
> 
> ```
> const { response } = await getProductsList({
>        pageParam: 0, // add this parameter
>       queryParams: { collection_id: collectionIds },
>       countryCode,
>     })
> ```

it's work!
