### ISSUE TITLE
Can't get styling to work with tailwind

### ISSUE THREAD

**Issue by JacquesFrost** [medusajs/nextjs-starter-medusa#385]
I've been trying to do basic things with tailwind like change colours of things by adding a class ex: bg-teal-600 but it doesn't work. I even tried changing config for tailwind. Is there any way to get tailwind to work with its original styling and not this reduced version. It seems almost any class I use doesn't work.

**Comment by Camirand** [comment]
Just tried to reproduce the issue with @latest
Went to template/nav, bg-slate-800 as a tryout and it works well. 

Did you init your tailwinds? Maybe a wrong installation on your side

No Issue with tailwinds and latest version of MedusaJS and it can be closed

![Capture d’écran 2024-10-27 091505](https://github.com/user-attachments/assets/93557068-b277-4a57-8602-1fa9570a706d)
