### ISSUE TITLE
can fix the browser errors? just annoying

### ISSUE THREAD

**Issue by sehor** [medusajs/nextjs-starter-medusa#389]
DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.

If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.

For more information, see https://radix-ui.com/primitives/docs/components/dialog

**Comment by VariableVic** [comment]
Can I ask you to create a new using the bug report template? Hard to reproduce and debug this issue based on this information.
