### ISSUE TITLE
Error 500 Internal Server Error - products/[handle]

### ISSUE THREAD

**Issue by jiaweing** [medusajs/nextjs-starter-medusa#391]
I had an issue with the production build causing error 500 when I visit any product page.
This error does not appear in development mode.

I had to remove this function from `src/app/[countryCode]/(main)/products/[handle]/page.tsx` for it to work.
```
export async function generateStaticParams() {
  const countryCodes = await listRegions().then(
    (regions) =>
      regions
        ?.map((r) => r.countries?.map((c) => c.iso_2))
        .flat()
        .filter(Boolean) as string[]
  )
  if (!countryCodes) {
    return null
  }
  const products = await Promise.all(
    countryCodes.map((countryCode) => {
      return getProductsList({ countryCode })
    })
  ).then((responses) =>
    responses.map(({ response }) => response.products).flat()
  )
  const staticParams = countryCodes
    ?.map((countryCode) =>
      products.map((product) => ({
        countryCode,
        handle: product.handle,
      }))
    )
    .flat()
  return staticParams
}
```

Not sure if this is just an edge case but hope it helps someone here.

**Comment by felixguerrero12** [comment]
You need to make sure all your products has the slug listed on the product.

**Comment by chillpilllike** [comment]
Thanks, I was stuck here for my production build. It helped.

**Comment by ouestlabs** [comment]
Issue https://github.com/medusajs/nextjs-starter-medusa/issues/396 

Add the following configuration to `/src/app/[countryCode]/(main)/products/[handle]/page.tsx`:

```ts
// ... existing imports ...

// Add this line at the top of the file
export const dynamic = "force-dynamic"

// ... rest of the file remains unchanged ...
```

**Comment by chillpilllike** [comment]
Thanks a simple line of code fixed the issue, what about the code offered in:

https://github.com/medusajs/nextjs-starter-medusa/pull/393

It was pushed to the repo update. should we stick to the old and add 
export const dynamic = "force-dynamic" 
or use the code 393

**Comment by ouestlabs** [comment]
> Thanks a simple line of code fixed the issue, what about the code offered in:
> 
> #393
> 
> It was pushed to the repo update. should we stick to the old and add export const dynamic = "force-dynamic" or use the code 393

Yo can use both the fix in https://github.com/medusajs/nextjs-starter-medusa/pull/393 work well.

`force-dynamic` forces the page to be dynamically rendered on every request, disables static optimization and caching, makes sure the page is server-side rendered (SSR) on each request

**Comment by ouestlabs** [comment]
The `DYNAMIC_SERVER_USAGE` error also affects collections and categories pages. 
Adding `export const dynamic = 'force-dynamic'` to:
- `/collections/[handle]/page.tsx`
- `/categories/[...category]/page.tsx`

resolves the issue for these pages as well. This happens when adding new collections/categories after the build.
