### ISSUE TITLE
upgrade nextjs 15

### ISSUE THREAD

**Issue by fuxianwei** [medusajs/nextjs-starter-medusa#392]
A new version of nextjs 15 has been out for a while, are there any plans to upgrade nextjs 15？

**Comment by chillpilllike** [comment]
For a while go with Munchies starter, its Nextjs 15 based

**Comment by fPolic** [comment]
hey @fuxianwei, you can check out Medusa starters here: https://medusajs.com/starters/. Some of them are built with Next 15.
