### ISSUE TITLE
Add dynamic route configuration for products page

### ISSUE THREAD

**Issue by ouestlabs** [medusajs/nextjs-starter-medusa#396]
The storefront currently experiences caching issues with product pages in production environments. To resolve this, we need to add the `dynamic = "force-dynamic"` export configuration in the products route.

### Proposed Changes

Add the following configuration to `/src/app/[countryCode]/(main)/products/[handle]/page.tsx`:

```typescript:/src/app/[countryCode]/(main)/products/[handle]/page.tsx
// ... existing imports ...

// Add this line at the top of the file
export const dynamic = "force-dynamic"

// ... rest of the file remains unchanged ...
```

### Why

- Prevents unwanted caching behavior in production environments
- Ensures product data is always fresh and up-to-date
- Fixes issues with product page rendering in hosted environments (e.g., Vercel, Railway)

### Additional Context

This is a recommended approach for handling dynamic routes in Next.js App Router, particularly for catch-all routes that need fresh data on each request.

**Comment by fPolic** [comment]
hey @ouestlabs thanks for the report. Would you be up for opening a PR for this one?

**Comment by ouestlabs** [comment]
> hey @ouestlabs thanks for the report. Would you be up for opening a PR for this one?

Hey @fPolic  sure

**Comment by ouestlabs** [comment]
PR: https://github.com/medusajs/nextjs-starter-medusa/pull/399

**Comment by prometixX** [comment]
I think this is the wrong approach. 
The starter is using `generateStaticParams` to statically pregenerate the routes for all product handles, which is recommended to get static pages which are much faster than dynamic routes. 

In next 15 we dont have caching active in most cases anyways, so the route `[countryCode]/(main)/products/[handle]` wont cache the api requests, so it will fetch from region and product api endpoints anyways. 

Just tested this, if you build the latest starter and check the log, you see that the routes for products are SSG but when you visit the pages its fetching the product from medusa server every time. 

I think we should even add caching to prevent long page loads and only revalidate via tags if products change. 
This way we can get much faster page loads and still have fresh data.

**Comment by ouestlabs** [comment]
Thank you @prometixX for your detailed analysis. I agree that my initial approach may not be optimal.

You make valid points about:
1. The existing `generateStaticParams` implementation providing static pre-generated pages
2. Next.js 15's default behavior already preventing unwanted caching
3. The current setup properly fetching fresh product data on each visit

I'll close this issue and PR since the caching concerns are already properly handled through the existing architecture. The better approach would be to focus on implementing proper caching with revalidation tags as you suggested, to optimize page load performance while maintaining data freshness.

Closing #399 as well.

**Comment by 420coupe** [comment]
> Thank you @prometixX for your detailed analysis. I agree that my initial approach may not be optimal.
> 
> You make valid points about:
> 
> 1. The existing `generateStaticParams` implementation providing static pre-generated pages
> 2. Next.js 15's default behavior already preventing unwanted caching
> 3. The current setup properly fetching fresh product data on each visit
> 
> I'll close this issue and PR since the caching concerns are already properly handled through the existing architecture. The better approach would be to focus on implementing proper caching with revalidation tags as you suggested, to optimize page load performance while maintaining data freshness.
> 
> Closing #399 as well.

was there a solution posted for this to do it the proper way?
