### ISSUE TITLE
Error during static page generation in production mode - 2.0

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/nextjs-starter-medusa#403]
I have a store of 20,000 products and growing when I launch the storefront in production mode it completes the static page generation after several failed attempts:

#14 52.33    Generating static pages (0/13755) ...
#14 70.00    Generating static pages (3438/13755) 
#14 70.32 Error: Error setting up the request: Bad Gateway
#14 70.32     at a (/app/.next/server/chunks/716.js:1:20071)
#14 70.32     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#14 70.32     at async w (/app/.next/server/chunks/439.js:35:4036) {
#14 70.32   digest: '1802650069'
#14 70.32 }
#14 70.32 eB [Error]: Bad Gateway
#14 70.32     at /app/.next/server/chunks/230.js:1:86020
#14 70.32     at Generator.next (<anonymous>)
#14 70.32     at a (/app/.next/server/chunks/230.js:1:85174)
#14 70.32     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#14 70.32   statusText: 'Bad Gateway',
#14 70.32   status: 502,
#14 70.32   digest: '1953811359'
#14 70.32 }
#14 71.34 eB [Error]: Bad Gateway
#14 71.34     at /app/.next/server/chunks/230.js:1:86020
#14 71.34     at Generator.next (<anonymous>)
#14 71.34     at a (/app/.next/server/chunks/230.js:1:85174)
#14 71.34     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#14 71.34   statusText: 'Bad Gateway',
#14 71.34   status: 502,
#14 71.34   digest: '1953811359'
#14 71.34 }
#14 71.34 Error: Error setting up the request: Bad Gateway
#14 71.34     at a (/app/.next/server/chunks/716.js:1:20071)
#14 71.34     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#14 71.34     at async w (/app/.next/server/chunks/439.js:35:4036) {
#14 71.34   digest: '1802650069'
#14 71.34 }
#14 71.34 eB [Error]: Bad Gateway
#14 71.34     at /app/.next/server/chunks/230.js:1:86020
#14 71.34     at Generator.next (<anonymous>)
#14 71.34     at a (/app/.next/server/chunks/230.js:1:85174)
#14 71.34     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#14 71.34   statusText: 'Bad Gateway',
#14 71.34   status: 502,
#14 71.34   digest: '1953811359'
#14 71.34 }
#14 71.34 Error: Error setting up the request: Bad Gateway
#14 71.34     at a (/app/.next/server/chunks/716.js:1:20071)
#14 71.34     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
#14 71.34     at async w (/app/.next/server/chunks/439.js:35:4036) {
#14 71.34   digest: '1802650069'
#14 71.34 }

a lot of error like this and then at the end

#14 78.51 eB [Error]: Bad Gateway
#14 78.51     at /app/.next/server/chunks/230.js:1:86020
#14 78.51     at Generator.next (<anonymous>)
#14 78.51     at a (/app/.next/server/chunks/230.js:1:85174)
#14 78.51     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#14 78.51   statusText: 'Bad Gateway',
#14 78.51   status: 502,
#14 78.51   digest: '1953811359'
#14 78.51 }
#14 78.51 eB [Error]: Bad Gateway
#14 78.51     at /app/.next/server/chunks/230.js:1:86020
#14 78.51     at Generator.next (<anonymous>)
#14 78.51     at a (/app/.next/server/chunks/230.js:1:85174)
#14 78.51     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
#14 78.51   statusText: 'Bad Gateway',
#14 78.51   status: 502,
#14 78.51   digest: '1953811359'
#14 78.51 }
#14 78.70  ✓ Generating static pages (13755/13755)
#14 78.92    Finalizing page optimization ...
#14 78.92    Collecting build traces ...
#14 78.93 
#14 78.95 Route (app)                                                                                                                                                                                           Size     First Load JS
#14 78.95 ┌ ○ /_not-found                                                                                                                                                                                       169 B          87.6 kB
#14 78.95 ├ ƒ /[countryCode]                                                                                                                                                                                    472 B           263 kB
#14 78.95 ├ ƒ /[countryCode]/account         

any fix for generating static pages without errors.

thanks

**Comment by chillpilllike** [comment]
#11 115.8  ⚠ Restarted static page generation for /mq/products/10-concrete-bent-anchor-bolts-58-11-x-10-hot-galvanized because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-1-34-wood-screwsslottedround-headsteelzinc-carton-1000-pcs because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-1-type-25-thread-cutting-screwsphillipspan-headsteelzinc-carton-5000-pcs because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-metal-roofing-screws-250-screws-x-3-light-gray-hex-head-sheet-metal-roof-screw-self-startingtapping-metal-to-wood-sheet-metal-siding-screws-epdm-washer-for-corrugated-roofing because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-2-coarse-drywall-screwsphillipsbugle-headsteelblack-phos-carton-1000-pcs because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-2-12-inch-316-marine-grade-stainless-steel-wood-screws-350-pieces-t25-star-drive-type-17-point-high-corrosion-resistance-for-saltwater-coastal-marine-construction-by-eagle-claw-fasteners because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-3-inch-304-grade-stainless-steel-deck-screws-wood-screws-flat-head-t25-star-drive-type-17-auger-tip-with-a-free-t25-star-drive-bit-for-all-outdoor-wood-construction350-pcs493-lbs because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-2-12-inch-stainless-steel-deck-screws-350-pieces-t25-star-torx-drive-flat-head-stainless-steel-screws-for-decks-docks-fencing-or-general-outdoor-construction-and-home-improvement-projects because it took more than 60 seconds
#11 115.8  ⚠ Restarted static page generation for /mr/products/10-x-4-coarse-drywall-screwsphillipsbugle-headst
#11 115.8 [output clipped, log limit 2MiB reached]
#11 172.5    Generating static pages (1256/13755) 
#11 176.6    Generating static pages (3438/13755) 
#11 188.0    Generating static pages (6877/13755) 
#11 202.3    Generating static pages (10316/13755) 
#11 271.7    Generating static pages (13740/13755) 
#11 271.9  ✓ Generating static pages (13755/13755)
#11 272.0    Finalizing page optimization ...
#11 272.0    Collecting build traces ...

**Comment by sradevski** [comment]
@chillpilllike can you maybe try throttling the requests to the BE when statically generating the pages? That's a lot of products, and if the requests happen very quickly it can overload the server.

**Comment by chillpilllike** [comment]
solved in the last stable update
