### ISSUE TITLE
yarn build not working because of unexpected JSON output

### ISSUE THREAD

**Issue by sergiocampama** [medusajs/nextjs-starter-medusa#406]
```
npm run build

> medusa-next@1.0.3 build
> next build

  ▲ Next.js 14.2.18
  - Environments: .env

   Creating an optimized production build ...
Failed to compile.

./node_modules/@medusajs/ui/dist/esm/components/calendar/calendar.js + 38 modules
Unexpected end of JSON input

./node_modules/@medusajs/ui/dist/esm/components/code-block/code-block.js + 2 modules
Unexpected end of JSON input

./node_modules/@medusajs/ui/dist/esm/components/date-picker/date-picker.js + 184 modules
Unexpected end of JSON input

./node_modules/@medusajs/ui/dist/esm/components/select/select.js + 36 modules
Unexpected end of JSON input

./node_modules/date-fns/esm/format/index.js + 18 modules
Unexpected end of JSON input


> Build failed because of webpack errors
```
This was using the latest version of the medusa starter pack with storefront. I can `yarn build` locally on my mac, and it succeeds on the dev version. But running `yarn build` on a server environment, with production data, I can't shake this error, and I can't see more logs to find out what the issue is.

I've disabled the `generateStaticParams` methods, thinking that it was about prerendering, but the issue persists. Anyone have any clue as to what might be happening?

I'm doing this build on a VPS server in digital ocean, ubuntu, if that helps. 

Does anyone know where I can see more errors from webpack so I can pinpoint the actual issue?

**Comment by christiananese** [comment]
Hey @sergiocampama ,
What version of yarn do you use on your local machine and which one on your server environment?

**Comment by sergiocampama** [comment]
Using 3.2.3 for both macOS and server environments.

**Comment by maxamed1st** [comment]
same issue

**Comment by avhn** [comment]
Downgrade node version to v20. You are probably using node v23.

**Comment by sergiocampama** [comment]
thanks @avhn , that was it, should we set this restriction on the package.json?

**Comment by avhn** [comment]
I don't think you need that. This could be a binary problem which they accidentally swapped with unstable version as stable while pushing to binary repo? Since this effects all nextjs projects for me, not medusa specific.
