### ISSUE TITLE
When product catalogue increases the add to cart appears very late

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/nextjs-starter-medusa#410]
Hello team,

I have a store of 10k products and when we visit the product page the add to cart appears very late 5-10 seconds and when we click on add to cart it again takes 5-10 seconds to add the product to cart.

Thank you!

**Comment by chillpilllike** [comment]
video link

https://1drv.ms/v/s!AjurUsnMUVFRg9s2291908HPTGhEaw?e=4quez1

**Comment by olivermrbl** [comment]
@chillpilllike, can you share more about your setup? Are your applications (Medusa + Next.js) deployed on infra or is this locally? If deployed, we'd like to know more about where and how beefy the machines are.

**Comment by chillpilllike** [comment]
<img width="674" alt="Screenshot 2024-11-26 at 2 42 39 pm" src="https://github.com/user-attachments/assets/92894554-8783-4564-88a2-9e841194aa56">

<img width="446" alt="Screenshot 2024-11-26 at 2 53 01 pm" src="https://github.com/user-attachments/assets/b74e1c18-66f8-4651-90d3-decdb6b7456e">


I have a bare metal dedicated server located in India and I am testing it from India. it has dual core cpu with total 64 cores and 256gb of ram. When I connect the same backend to a new postgres instance then the storefront works fine. Currently there is nothing else installed on the server other than this storefront + backend server + worker + postgres. ram and cpu usage always remains under 5%

**Comment by chillpilllike** [comment]
<img width="339" alt="Screenshot 2024-11-26 at 3 57 39 pm" src="https://github.com/user-attachments/assets/87670cbb-2dc0-4a43-b6f1-c0ee350d26c6">


when we click on add to cart this log appears in worker mode server.

**Comment by chillpilllike** [comment]
I have set up another website with a large dataset, and I’m encountering the same issue. When the number of products are small, the website performs well and remains fast. However, as the number of products increases, the performance significantly deteriorates. The homepage, store page, product pages, related products section, add-to-cart functionality, and the add-to-cart popup experience severe slowdowns, often exceeding 10 seconds giving a bad experience.

https://nutricity-com-au-nutricity-au-storefront.g5edov.easypanel.host

Backend had not a single issue while importing all the products.

Please suggest a solution to address this issue.

**Comment by chillpilllike** [comment]
Think nextjs will alway be slow for large datasets.
