### ISSUE TITLE
Cart Page Refresh Displays Empty Cart

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/nextjs-starter-medusa#415]
When the cart page is refreshed, items in the cart initially show a quantity of 0. However, when revisiting the cart page after adding another product, the correct quantities in the cart are displayed. 

video: 
https://1drv.ms/v/s!AjurUsnMUVFRg9s3gIu2XlgwLbygjQ?e=bYyAew

**Comment by thetutlage** [comment]
Hello @chillpilllike 

Just gave it a try with a new app and all seems to be working fine on my end. If you have customized anything, then it will be nice to look at that logic.

Also, it will be great if you can share what exactly is broken and then we can look into fixing it.

https://github.com/user-attachments/assets/cbb93fbc-f1ce-4c1b-aee7-fee3fb5e3322
