### ISSUE TITLE
No products returned by getProductsList

### ISSUE THREAD

**Issue by shaun-xenon** [medusajs/nextjs-starter-medusa#418]
The calculation of the offset used by the getProductsList() function is wrong and always results in an offset equal to the limit. This causes the query to return no products.

**Comment by RoxDevvv** [comment]
mine was working and stopped working as soon as i uploaded product

**Comment by VariableVic** [comment]
I did some refactoring on the data fetching / caching. Couldn't reproduce this issue on the lastest version. Can you please pull the latest and let me know if that fixes your issue?
