### ISSUE TITLE
Deploy to Cloudflare Pages - `fetch` issue

### ISSUE THREAD

**Issue by dannikl** [medusajs/nextjs-starter-medusa#421]
Hello!

> I'm trying to deploy a storefront for MedusaJS v2 on Cloudflare Pages using next-on-pages, however for some reason `fetch` is not fetching products from an endpoint.

<img src="https://uploads.linear.app/6afc998d-0125-4bd5-a791-94d2bbd42b7c/cf4f8523-fcbf-4647-987e-01756d0d820a/769e25be-4ebe-45b9-af8d-7baaaf7dcf5a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZhZmM5OThkLTAxMjUtNGJkNS1hNzkxLTk0ZDJiYmQ0MmI3Yy9jZjRmODUyMy1mY2JmLTQ2NDctOTg3ZS0wMTc1NmQwZDgyMGEvNzY5ZTI1YmUtNGViZS00NWI5LWFmOGQtN2JhYWFmN2RjZjVhIiwiaWF0IjoxNzMzMzM3ODM0LCJleHAiOjMzMzAzODk3ODM0fQ.eCERH6P852QEO20rQBnmHfV95DnnPWhvxEsS-Dw_9UA " alt="image" width="1491" />

I have checked Cloudflare pages documentation and change the `runtime` to `edge` and set `auth.type` to `jwt` from config to disable fetch credentials but still have the same issue.

**Comment by dannikl** [comment]
Hey @olivermrbl , here is the cloudflare pages URL: https://cart-staging.pilotinstitute.com/dk/store

**Comment by olivermrbl** [comment]
Do you have any server logs displaying an error? I can't seem to find anything about this other than a bunch of old issues describing problems with SSR on Cloudflare Pages due to missing fetch compatibility.

**Comment by dannikl** [comment]
@olivermrbl , in the server logs, I see only the request made from middleware to get regions but I don't see the request to fetch products. Storefront is not calling products endpoint.

**Comment by dannikl** [comment]
This is what I have catched here https://github.com/medusajs/nextjs-starter-medusa/blob/main/src/lib/data/regions.ts#L62
<img width="951" alt="image" src="https://github.com/user-attachments/assets/31292519-46da-4a6c-8c86-e82e24d7b114">

**Comment by dannikl** [comment]
Thanks @sgirones . Exists any quick workaround for that issue, please? Maybe, I can create a custom sdk client?

**Comment by sgirones** [comment]
can you try his snapshot? https://github.com/medusajs/medusa/pull/10446#issuecomment-2519786252

The PR checks if the credentials field is supported before adding it

**Comment by dannikl** [comment]
Thanks @sgirones , works with this snapshot! 
<img width="1191" alt="image" src="https://github.com/user-attachments/assets/3c74bdb3-c461-42d8-8c87-bf88f37c868c">
