### ISSUE TITLE
Region Selection  reset to default state, but UI dropdown still show previous selected region

### ISSUE THREAD

**Issue by AlexDigital974** [medusajs/nextjs-starter-medusa#44]
### Describe the bug

You need to have multiple Region setup, pick one that not your first region ,latest you created and do a checkout .
 Check with an address for that region well its mandatory anyways.
all good.

Now try to do a second checkout and error in console.

```
Request URL: http://localhost:9000/store/carts/cart_01G8J6CRJV2FK08A6394QW8HM7
Request Method: POST
Status Code: 400 Bad Request

{type: "invalid_data", message: "Shipping country must be in the cart region"}
message: "Shipping country must be in the cart region"
type: "invalid_data"
```

I can also see my tax is different now but the UI dropdown for region is still showing the correct region
But look like the Actual state of the save region have reverse to default( i guess the first one not sure)

### Additional context

If i re-reselect the region from the the dropdown, i can checkout

### Expected behavior

if a region is selected/loaded, it stay

**Comment by kasperkristensen** [comment]
Fixed in #49
