### ISSUE TITLE
Invalid next.config.js options detected

### ISSUE THREAD

**Issue by lack-of-gravitas** [medusajs/nextjs-starter-medusa#56]
1 - run yarn create medusa-app
2 - cd into /my-medusa-store/storefront
3 - yarn start as instructed
4 - following error received

![image](https://user-images.githubusercontent.com/10094964/183249061-fdfd70ca-a0b6-410b-98a9-6446f83d136c.png)

`yarn run v1.22.19
$ next start -p 8000
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
next.config.js {
  "features": {
    "search": false
  },
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
warn  - Invalid next.config.js options detected: 
  - The root value has an unexpected property, features, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).

See more info here: https://nextjs.org/docs/messages/invalid-next-config
Error: Could not find a production build in the '/home/prasit/Documents/praxio/my-medusa-store/storefront/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/home/prasit/Documents/praxio/my-medusa-store/storefront/node_modules/next/dist/server/next-server.js:115:23)
    at new Server (/home/prasit/Documents/praxio/my-medusa-store/storefront/node_modules/next/dist/server/base-server.js:70:29)
    at new NextNodeServer (/home/prasit/Documents/praxio/my-medusa-store/storefront/node_modules/next/dist/server/next-server.js:62:9)
    at NextServer.createServer (/home/prasit/Documents/praxio/my-medusa-store/storefront/node_modules/next/dist/server/next.js:128:16)
    at async /home/prasit/Documents/praxio/my-medusa-store/storefront/node_modules/next/dist/server/next.js:137:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by kasperkristensen** [comment]
Hi @lack-of-gravitas, I will look into fixing the warning. But it is not related to the error you are receiving.

You are trying to run a production build that does not exist. To start the starter in `development` mode, use the command `yarn dev`. 

If you want to start a production build, you will first need to build it. You do this by first running `yarn build` and after that is completed run `yarn start`.

**Comment by kasperkristensen** [comment]
fixed in #57
