### ISSUE TITLE
Error: read ECONNRESET on product page

### ISSUE THREAD

**Issue by Boumour** [medusajs/nextjs-starter-medusa#61]
wait  - compiling...
event - compiled client and server successfully in 457 ms (1516 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling /products/[handle] (client and server)...
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
event - compiled client and server successfully in 217 ms (1673 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 109 ms (1673 modules)
error - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  type: 'Error',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    transformRequest: [ null ],
    transformResponse: [ null ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.24.0'
    },
    baseURL: 'http://localhost:9000',
    raxConfig: {
      retry: 3,
      backoffType: 'exponential',
      currentRetryAttempt: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      checkRetryAfter: true,
      maxRetryAfter: 300000,
      statusCodesToRetry: [Array]
    },
    method: 'get',
    withCredentials: true,
    url: '/store/products?limit=25',
    json: true
  },
  code: 'ECONNRESET',
  status: null,
  page: '/products/[handle]'
}
error - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  type: 'Error',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    transformRequest: [ null ],
    transformResponse: [ null ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.24.0'
    },
    baseURL: 'http://localhost:9000',
    raxConfig: {
      retry: 3,
      backoffType: 'exponential',
      currentRetryAttempt: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      checkRetryAfter: true,
      maxRetryAfter: 300000,
      statusCodesToRetry: [Array]
    },
    method: 'get',
    withCredentials: true,
    url: '/store/products?limit=25',
    json: true
  },
  code: 'ECONNRESET',
  status: null,
  page: '/products/[handle]'
}

**Comment by kasperkristensen** [comment]
@Boumour answered you here https://github.com/medusajs/medusa/issues/2053#issuecomment-1217671694, please refrain from cross posting issues across repos in the future thanks 😄
