### ISSUE TITLE
netlify deployment error

### ISSUE THREAD

**Issue by Holvert-P** [medusajs/nextjs-starter-medusa#65]
After clicking the button to deploy in netlify, configure the URL of my backend and deploy, I get this error during the build

**Comment by kasperkristensen** [comment]
@Holvert-P Could you please share the error that you are receiving? 🙂

**Comment by Holvert-P** [comment]
### **this is the error i get**


12:07:53 PM: Build ready to start
12:07:58 PM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
12:07:58 PM: build-image tag: v4.10.1
12:07:58 PM: buildbot version: 67e75f1ba713a8213d4b5a8ccf9708af751e2390
12:07:58 PM: Fetching cached dependencies
12:07:58 PM: Failed to fetch cache, continuing with build
12:07:58 PM: Starting to prepare the repo for build
12:07:58 PM: No cached dependencies found. Cloning fresh repo
12:07:58 PM: git clone https://github.com/medusajs/nextjs-starter-medusa
12:07:59 PM: Preparing Git Reference refs/heads/main
12:07:59 PM: Parsing package.json dependencies
12:08:00 PM: Starting build script
12:08:00 PM: Installing dependencies
12:08:00 PM: Python version set to 2.7
12:08:00 PM: Downloading and installing node v16.17.0...
12:08:01 PM: Downloading https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz...
12:08:01 PM: Computing checksum with sha256sum
12:08:01 PM: Checksums matched!
12:08:03 PM: Now using node v16.17.0 (npm v8.15.0)
12:08:03 PM: Started restoring cached build plugins
12:08:03 PM: Finished restoring cached build plugins
12:08:03 PM: Attempting ruby version 2.7.2, read from environment
12:08:04 PM: Using ruby version 2.7.2
12:08:04 PM: Using PHP version 8.0
12:08:04 PM: Started restoring cached yarn cache
12:08:04 PM: Finished restoring cached yarn cache
12:08:04 PM: No yarn workspaces detected
12:08:04 PM: Started restoring cached node modules
12:08:04 PM: Finished restoring cached node modules
12:08:04 PM: Installing NPM modules using Yarn version 1.22.10
12:08:05 PM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
12:08:05 PM: npm WARN config location in the cache, and they are managed by
12:08:05 PM: npm WARN config     [`cacache`](http://npm.im/cacache).
12:08:05 PM: yarn install v1.22.10
12:08:05 PM: [1/4] Resolving packages...
12:08:05 PM: [2/4] Fetching packages...
12:08:20 PM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
12:08:20 PM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-android-arm-eabi@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-android-arm-eabi@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-android-arm-eabi@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info @next/swc-android-arm64@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-android-arm64@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-android-arm64@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info @next/swc-darwin-arm64@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-darwin-arm64@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-darwin-arm64@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info @next/swc-darwin-x64@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-darwin-x64@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-freebsd-x64@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-freebsd-x64@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-linux-arm-gnueabihf@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info "@next/swc-linux-arm-gnueabihf@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-linux-arm64-gnu@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info "@next/swc-linux-arm64-gnu@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-linux-arm64-musl@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info "@next/swc-linux-arm64-musl@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-win32-arm64-msvc@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-win32-arm64-msvc@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-win32-arm64-msvc@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info @next/swc-win32-ia32-msvc@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-win32-ia32-msvc@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: info @next/swc-win32-ia32-msvc@12.2.0: The CPU architecture "x64" is incompatible with this module.
12:08:20 PM: info @next/swc-win32-x64-msvc@12.2.0: The platform "linux" is incompatible with this module.
12:08:20 PM: info "@next/swc-win32-x64-msvc@12.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
12:08:20 PM: [3/4] Linking dependencies...
12:08:20 PM: warning " > @medusajs/medusa@1.3.5" has unmet peer dependency "medusa-interfaces@1.3.2".
12:08:20 PM: warning " > @medusajs/medusa@1.3.5" has unmet peer dependency "typeorm@0.2.x".
12:08:20 PM: warning "@medusajs/medusa > ioredis-mock@5.9.1" has unmet peer dependency "redis-commands@1.x".
12:08:20 PM: warning " > react-instantsearch-hooks-web@6.29.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
12:08:20 PM: warning "react-instantsearch-hooks-web > instantsearch.js@4.42.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
12:08:20 PM: warning "react-instantsearch-hooks-web > react-instantsearch-hooks@6.29.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
12:08:20 PM: warning "react-instantsearch-hooks-web > instantsearch.js > algoliasearch-helper@3.9.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
12:08:27 PM: [4/4] Building fresh packages...
12:08:37 PM: Done in 32.21s.
12:08:37 PM: NPM modules installed using Yarn
12:08:37 PM: Started restoring cached go cache
12:08:37 PM: Finished restoring cached go cache
12:08:37 PM: Installing Go version 1.17 (requested 1.17)
12:08:41 PM: unset GOOS;
12:08:41 PM: unset GOARCH;
12:08:41 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
12:08:41 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
12:08:41 PM: go version >&2;
12:08:41 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
12:08:41 PM: go version go1.17 linux/amd64
12:08:41 PM: Installing missing commands
12:08:41 PM: Verify run directory
12:08:42 PM: ​
12:08:42 PM: ────────────────────────────────────────────────────────────────
12:08:42 PM:   Netlify Build                                                 
12:08:42 PM: ────────────────────────────────────────────────────────────────
12:08:42 PM: ​
12:08:42 PM: ❯ Version
12:08:42 PM:   @netlify/build 27.16.1
12:08:42 PM: ​
12:08:42 PM: ❯ Flags
12:08:42 PM:   baseRelDir: true
12:08:42 PM:   buildId: 63163af97f1ade24376d8368
12:08:42 PM:   deployId: 63163af97f1ade24376d836a
12:08:42 PM: ​
12:08:42 PM: ❯ Current directory
12:08:42 PM:   /opt/build/repo
12:08:42 PM: ​
12:08:42 PM: ❯ Config file
12:08:42 PM:   /opt/build/repo/netlify.toml
12:08:42 PM: ​
12:08:42 PM: ❯ Context
12:08:42 PM:   production
12:08:43 PM: ​
12:08:43 PM: ❯ Installing plugins
12:08:43 PM:    - @netlify/plugin-nextjs@4.21.1
12:08:49 PM: ​
12:08:49 PM: ❯ Loading plugins
12:08:49 PM:    - @netlify/plugin-nextjs@4.21.1 from Netlify app
12:08:50 PM: ​
12:08:50 PM: ────────────────────────────────────────────────────────────────
12:08:50 PM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
12:08:50 PM: ────────────────────────────────────────────────────────────────
12:08:50 PM: ​
12:08:50 PM: No Next.js cache to restore.
12:08:50 PM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
12:08:50 PM: ​
12:08:50 PM: (@netlify/plugin-nextjs onPreBuild completed in 18ms)
12:08:50 PM: ​
12:08:50 PM: ────────────────────────────────────────────────────────────────
12:08:50 PM:   2. Build command from Netlify app                             
12:08:50 PM: ────────────────────────────────────────────────────────────────
12:08:50 PM: ​
12:08:50 PM: $ yarn build
12:08:50 PM: yarn run v1.22.10
12:08:51 PM: $ next build
12:08:51 PM: next.config.js {
12:08:51 PM:   "reactStrictMode": true,
12:08:51 PM:   "images": {
12:08:51 PM:     "domains": [
12:08:51 PM:       "medusa-public-images.s3.eu-west-1.amazonaws.com",
12:08:51 PM:       "localhost"
12:08:51 PM:     ]
12:08:51 PM:   },
12:08:51 PM:   "env": {}
12:08:51 PM: }
12:08:51 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
12:08:51 PM: info  - Linting and checking validity of types...
12:08:59 PM: info  - Creating an optimized production build...
12:09:06 PM: Browserslist: caniuse-lite is outdated. Please run:
12:09:06 PM:   npx browserslist@latest --update-db
12:09:06 PM:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
12:09:18 PM: info  - Compiled successfully
12:09:18 PM: info  - Collecting page data...
12:10:24 PM: warn  - Restarted collecting page data for /collections/[id] because it took more than 60 seconds
12:10:24 PM: warn  - See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
12:10:24 PM: warn  - Restarted collecting page data for /products/[handle] because it took more than 60 seconds
12:11:25 PM: > Build error occurred
12:11:25 PM: Error: Collecting page data for /collections/[id] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
12:11:25 PM:     at onRestart (/opt/build/repo/node_modules/next/dist/build/index.js:553:35)
12:11:25 PM:     at Worker.isPageStatic (/opt/build/repo/node_modules/next/dist/lib/worker.js:48:40)
12:11:25 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
12:11:25 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:79:20)
12:11:25 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:625:52
12:11:25 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:79:20)
12:11:25 PM:     at async Promise.all (index 11)
12:11:25 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:599:17
12:11:25 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:79:20)
12:11:25 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:577:170
12:11:25 PM: error Command failed with exit code 1.
12:11:25 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:11:25 PM: ​
12:11:25 PM: ────────────────────────────────────────────────────────────────
12:11:25 PM:   "build.command" failed                                        
12:11:25 PM: ────────────────────────────────────────────────────────────────
12:11:25 PM: ​
12:11:25 PM:   Error message
12:11:25 PM:   Command failed with exit code 1: yarn build
12:11:25 PM: ​
12:11:25 PM:   Error location
12:11:25 PM:   In Build command from Netlify app:
12:11:25 PM:   yarn build
12:11:25 PM: ​
12:11:25 PM:   Resolved config
12:11:25 PM:   build:
12:11:25 PM:     command: yarn build
12:11:25 PM:     commandOrigin: ui
12:11:25 PM:     environment:
12:11:25 PM:       - NEXT_PUBLIC_MEDUSA_BACKEND_URL
12:11:25 PM:       - NEXT_PRIVATE_TARGET
12:11:25 PM:     publish: /opt/build/repo/.next
12:11:25 PM:     publishOrigin: ui
12:11:25 PM:   plugins:
12:11:25 PM:     - inputs: {}
12:11:25 PM:       origin: ui
12:11:25 PM:       package: '@netlify/plugin-nextjs'
12:11:26 PM: Caching artifacts
12:11:26 PM: Started saving node modules
12:11:26 PM: Finished saving node modules
12:11:26 PM: Started saving build plugins
12:11:26 PM: Finished saving build plugins
12:11:26 PM: Started saving yarn cache
12:11:31 PM: Finished saving yarn cache
12:11:31 PM: Started saving pip cache
12:11:31 PM: Finished saving pip cache
12:11:31 PM: Started saving emacs cask dependencies
12:11:31 PM: Finished saving emacs cask dependencies
12:11:31 PM: Started saving maven dependencies
12:11:31 PM: Finished saving maven dependencies
12:11:31 PM: Started saving boot dependencies
12:11:31 PM: Finished saving boot dependencies
12:11:31 PM: Started saving rust rustup cache
12:11:31 PM: Finished saving rust rustup cache
12:11:31 PM: Started saving go dependencies
12:11:31 PM: Finished saving go dependencies
12:11:33 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:11:33 PM: Creating deploy upload records
12:11:34 PM: Failing build: Failed to build site
12:11:34 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
12:11:34 PM: Finished processing build request in 3m36.139703252s
