### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by AviAvinav** [medusajs/nextjs-starter-medusa#68]
I was trying out the nextjs-starter and I have been running into this error when I start the development server with `yarn dev`. There doesn't seem to be any error in the console.

This is the output:

```
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
info  - Loaded env from C:\Users\Acer\Desktop\Development\blogs-tut\medusa\my-medusa-storefront\.env.local
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
event - compiled client and server successfully in 43.3s (1054 modules)
wait  - compiling...
event - compiled successfully in 442 ms (1011 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 5.9s (1645 modules)
```

But the problem is when I go to localhost:8000 to check it, this is the error I get:

<img src="https://i.imgur.com/lHO6X9x.png"  />

**Comment by kasperkristensen** [comment]
Hi @AviAvinav, you most likely don't have a Medusa server running, or at least not on the port that the starter expects it to be.

If not then please share the failed request from your network tab, so we can better assist you 😄

**Comment by AviAvinav** [comment]
Ah, alright it works now! I am stupid
