### ISSUE TITLE
Product pages does not load - stuck on pending

### ISSUE THREAD

**Issue by itailulu** [medusajs/nextjs-starter-medusa#70]
I installed the starter and most pages work correctly, except for the product page.
When navigating to a product page (either by clicking a product in the collections page, or pasting the url into the address bar) the document is stuck on `pending` in the network tab, with the following url: `http://localhost:8333/_next/data/development/products/sweatshirt.json?handle=sweatshirt`

![image](https://user-images.githubusercontent.com/4988811/191690522-e2ad08a8-e05e-4f7e-b2d4-3d3001b00b81.png)

I tried to change ports, restarted the server, Chrome and Safari, cleared cache, and more. Nothing worked :(
Also might be worth mentioning that on Firefox all API requests are stuck in a weird state, seems like they are not even pending. I'm not sure it's related, as other browsers are working mostly fine. Attaching screenshot:
![image](https://user-images.githubusercontent.com/4988811/191692818-dfad986c-a15b-4d3c-aaf3-6bfd5253eef5.png)

##### Environment details:
```
Mac Mojave 10.14.6
Running backend on Docker
Storefront on host machine with `yarn dev`
Project generated from this template yesterday
Node v16.17.0
Yarn 1.22.19
```

**Comment by R3D2** [comment]
For my part, everything works on dev, but in prod, all the product pages "504 - Gateway Timeout".

**Comment by Zbaskik** [comment]
Hi @itailulu have you found any fix for that?
