### ISSUE TITLE
Auto Select Country

### ISSUE THREAD

**Issue by stnguyen90** [medusajs/nextjs-starter-medusa#73]
Currently, the starter will automatically select the region if provided by the response from the Create a Cart API call, but it won't select the country even if `cart.shipping_address.country_code` is set.

**Comment by kasperkristensen** [comment]
Hi @stnguyen90, 

If you are up for it then feel free to open a PR with this, I won't be adding it, as the starter is just meant as a starter for users to build onto themselves, and I think it does that job fine as is. But I would definitely not oppose merging it if such a PR was opened 😄

**Comment by stnguyen90** [comment]
@kasperkristensen, I'm open to creating a PR. Can this be left open and me assigned to it to track the work?

**Comment by kasperkristensen** [comment]
Sure thing @stnguyen90, I've assigned you 😄
