### ISSUE TITLE
MIT license missing

### ISSUE THREAD

**Issue by gitusertd** [medusajs/nextjs-starter-medusa#85]
**Problem**: There is no LICENSE file in this repository.
**Context**: Since README.md states that this repository is licensed under the MIT license, as well as many are using create-next-app using the template of this repo to create the initial commit in their project.
**Question**: Is this repo MIT licensed? Or a hidden vendor lock-in trick?
**Solution**: adding the LICENSE file will bring transparency which is important to Medusa users.

**Comment by kasperkristensen** [comment]
Thanks for pointing it out, just added it :)
