### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by MatteoGauthier** [medusajs/nextjs-starter-medusa#87]
These endpoints return 503 http error in the demo app https://next.medusajs.com/store
- https://production-like-starter.herokuapp.com/store/carts
-  https://production-like-starter.herokuapp.com/store/customers/me
- https://production-like-starter.herokuapp.com/store/regions
- https://production-like-starter.herokuapp.com/store/products?limit=12&offset=0&is_giftcard=false
- https://production-like-starter.herokuapp.com/store/collections?offset=0
- https://production-like-starter.herokuapp.com/store/collections

**Comment by kasperkristensen** [comment]
Thanks for reporting it @MatteoGauthier  

@olivermrbl can we get the server up and running again?

**Comment by stephane-klein** [comment]
@kasperkristensen same error at 2023-03-18 :thinking:.

**Comment by basanta-goswami** [comment]
Seems like there the demo https://next.medusajs.com/ is still broken. The backend APIs are failing because of CORS configuration.

**Comment by lukebars** [comment]
Still broken 👀

**Comment by MatteoGauthier** [comment]
Thanks @kasperkristensen for the fix, Just wanted to check if there are any specific steps we need to take on our instance to avoid this bug in the future. It would be helpful if you could share some details on how you fixed the issue. Thanks again, byee!

**Comment by kasperkristensen** [comment]
@MatteoGauthier Not sure what you mean? The reason why the demo was broken was that the server got taken down by Heroku, because we forgot to update it when their old Redis service was deprecated, and then we just kept not getting around to setting up the server again 😄
