### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by vupham84** [medusajs/nextjs-starter-medusa#9]
Hi, I follow the instruction but get the following error when I start the web app.

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

Source
utils/prices.js (24:64) @ eval

  22 | 
  23 |   let moneyAmount = variant.prices.find(
> 24 |     (p) => p.currency_code.toLowerCase() === cart.currency_code.toLowerCase()
     |                                                                ^
  25 |   );
  26 | 
  27 |   if (moneyAmount && moneyAmount.amount) {

**Comment by noahrinehart** [comment]
I believe it is because `cart.currency_code` [here](https://github.com/medusajs/nextjs-starter-medusa/blob/main/utils/prices.js#L24) should be `cart.region.currency_code` instead, which is what it is like on [L39](https://github.com/medusajs/nextjs-starter-medusa/blob/main/utils/prices.js#L39)

**Comment by kasperkristensen** [comment]
@vupham84 @noahrinehart @kjcsb1 Thank you for pointing out the error, the issue should be resolved now 👍
