### ISSUE TITLE
Unable to clone and install medusa starter due to sqlite3 version

### ISSUE THREAD

**Issue by ritmillio** [medusajs/nextjs-starter-medusa#90]
I am not sure if someone else ran into this issue but for me It's not possible to simple create a new storefront following medusa documentation. After a short investigation (my current node version is 19) you need to use node18 or below. In order to use this template sqlite3 version needs to be upgraded at least to v5.0.3.

**Comment by HadiHassan22** [comment]
same issue here, cannot create project neither with node 18 nor node 16 (lts/gallium)

**Comment by alexshyba** [comment]
Had the same issue with 18.12.0, and installing 18.13.0 helped me 🤷🏻

**Comment by minescoviciu** [comment]
Quick fix for this would be to install globally sqlite3@5.0.4 . I had this problem solved on Apple M1 pro.

Also, it is falling to build it from source because it is using python 2..
